const { withAndroidManifest, withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

// Adds a static Android "App Shortcut" (long-press the launcher icon) that
// jumps straight to sharing today's verse, without opening the app's normal
// UI first. Android always has to launch an Activity to handle a shortcut
// tap — there's no way to fire the OS share sheet from a purely background
// task — but this at least skips in-app navigation (open app, find today's
// verse, tap share). The JS side that actually calls Share.share() lives in
// App.js, triggered by the barnabas-journal://share-today deep link below.
//
// This has to be a real config plugin (not a checked-in android/ folder)
// because this project uses Continuous Native Generation: `eas build` runs
// `expo prebuild` fresh every time, so anything under android/ that isn't
// generated by a plugin is discarded.

const SHORTCUT_ID = "share_today_verse";
const DEEP_LINK = "barnabas-journal://share-today";

function withShareShortcutResources(config) {
  return withDangerousMod(config, [
    "android",
    (config) => {
      const resDir = path.join(config.modRequest.platformProjectRoot, "app/src/main/res");

      const xmlDir = path.join(resDir, "xml");
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, "shortcuts.xml"),
        `<?xml version="1.0" encoding="utf-8"?>
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
  <shortcut
    android:shortcutId="${SHORTCUT_ID}"
    android:enabled="true"
    android:icon="@mipmap/ic_launcher"
    android:shortcutShortLabel="@string/share_shortcut_short_label"
    android:shortcutLongLabel="@string/share_shortcut_long_label">
    <intent
      android:action="android.intent.action.VIEW"
      android:data="${DEEP_LINK}" />
  </shortcut>
</shortcuts>
`
      );

      const valuesDir = path.join(resDir, "values");
      fs.mkdirSync(valuesDir, { recursive: true });
      fs.writeFileSync(
        path.join(valuesDir, "shortcuts_strings.xml"),
        // Android string resources require a literal apostrophe to be
        // escaped (\') — an unescaped one fails AAPT resource compilation
        // (caught by an actual EAS build: "Invalid unicode escape sequence
        // in string" / "does not contain a valid string resource").
        `<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="share_shortcut_short_label">Share Verse</string>
  <string name="share_shortcut_long_label">Share Today\\'s Verse</string>
</resources>
`
      );

      return config;
    },
  ]);
}

function withShareShortcutManifest(config) {
  return withAndroidManifest(config, (config) => {
    const application = config.modResults.manifest.application[0];
    const mainActivity = application.activity.find(
      (activity) => activity.$["android:name"] === ".MainActivity"
    );
    if (mainActivity) {
      if (!mainActivity["meta-data"]) mainActivity["meta-data"] = [];
      const alreadyPresent = mainActivity["meta-data"].some(
        (entry) => entry.$["android:name"] === "android.app.shortcuts"
      );
      if (!alreadyPresent) {
        mainActivity["meta-data"].push({
          $: {
            "android:name": "android.app.shortcuts",
            "android:resource": "@xml/shortcuts",
          },
        });
      }
    }
    return config;
  });
}

module.exports = function withShareShortcut(config) {
  config = withShareShortcutResources(config);
  config = withShareShortcutManifest(config);
  return config;
};
