// 366 quotes and short stories on the power of encouragement and hope —
// one for every day of the year, including a leap day, with no repeats.

const WISDOM = [
  {"type":"story","title":null,"text":"An overwhelmed waiter, on a cold winter evening: a child waved and said hello, like it was the easiest thing in the world. It's a small story, but it's one worth telling."},
  {"type":"quote","text":"Wherever there is a human being, there is an opportunity for a kindness.","source":"Seneca"},
  {"type":"story","title":null,"text":"An anxious traveler, during a long hospital wait: someone paid off the balance on a stranger's layaway order. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A single father, on a rainy Tuesday morning: someone simply said, \"I'm glad you're here\". It was enough to help them keep going."},
  {"type":"story","title":null,"text":"An elderly man, on a quiet Sunday afternoon: someone simply said, \"I'm glad you're here\". They never forgot it."},
  {"type":"story","title":null,"text":"A tired father, during a difficult week at work: an old friend called out of nowhere, just to check in. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, on a rainy Tuesday morning: an old friend called out of nowhere, just to check in. They passed the kindness on to someone else that same week."},
  {"type":"quote","text":"A hedge between keeps friendship green.","source":"Proverb"},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, on their first day somewhere new: an anonymous gift appeared at their door that week. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A struggling college student, on a rainy Tuesday morning: someone remembered a small detail about their life and asked about it. It reminded them that people are still good."},
  {"type":"quote","text":"The soul would have no rainbow had the eyes no tears.","source":"John Vance Cheney"},
  {"type":"quote","text":"A single act of kindness throws out roots in all directions, and the roots spring up and make new trees.","source":"Amelia Earhart"},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, at the end of a long line: someone sat down beside them and just listened. For the first time in weeks, they felt seen."},
  {"type":"quote","text":"Every saint has a past, and every sinner has a future.","source":"Oscar Wilde"},
  {"type":"story","title":null,"text":"A soldier home on leave, in a waiting room: someone let them go first in line with a warm smile. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A little girl, on the bus home from a hard shift: a note was left in a library book that read, \"you are not alone\". They never forgot it."},
  {"type":"story","title":null,"text":"A grieving widow, on the bus home from a hard shift: a stranger's small joke made them laugh for the first time in days. That one moment carried them through a hard season."},
  {"type":"quote","text":"Hope begins in the dark, the stubborn hope that if you just show up and try to do the right thing, the dawn will come.","source":"Anne Lamott"},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, after a long, discouraging day: someone paid off the balance on a stranger's layaway order. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A new student, on a quiet Sunday afternoon: a coworker covered their shift without being asked twice. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A first-time volunteer, while sitting alone at lunch: an old friend called out of nowhere, just to check in. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, during a difficult week at work: an anonymous gift appeared at their door that week. It was enough to help them keep going."},
  {"type":"quote","text":"The soul is healed by being with children.","source":"Fyodor Dostoevsky"},
  {"type":"story","title":null,"text":"A stranger at the bus stop, on their first day somewhere new: a child waved and said hello, like it was the easiest thing in the world. It gave them the strength to face what came next."},
  {"type":"quote","text":"How wonderful it is that nobody need wait a single moment before starting to improve the world.","source":"Anne Frank"},
  {"type":"story","title":null,"text":"A coworker having a hard week, on a rainy Tuesday morning: someone sat down beside them and just listened. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A tired commuter, at the end of a long line: a stranger paid for their coffee and walked away before they could say thank you. They found themselves smiling the rest of the day."},
  {"type":"quote","text":"Start each day with a grateful heart.","source":"Unknown"},
  {"type":"quote","text":"Faith is taking the first step even when you don't see the whole staircase.","source":"Martin Luther King Jr."},
  {"type":"story","title":null,"text":"A soldier home on leave, on a rainy Tuesday morning: a passerby offered their umbrella without a word. It gave them the strength to face what came next."},
  {"type":"quote","text":"The best portion of a good person's life: their little, nameless, unremembered acts of kindness and love.","source":"William Wordsworth"},
  {"type":"story","title":null,"text":"A struggling college student, after a sleepless night: someone drove out of their way just to bring them home. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A quiet teenager, while sitting alone at lunch: a note was left in a library book that read, \"you are not alone\". It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A shop owner, after a sleepless night: a passerby offered their umbrella without a word. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A young intern, in the checkout line at a grocery store: a stranger's small joke made them laugh for the first time in days. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, in a crowded train station: someone drove out of their way just to bring them home. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A new student, just before a hard appointment: an old friend called out of nowhere, just to check in. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A soldier home on leave, during a difficult week at work: a stranger carried their bags up the stairs without being asked. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, at the end of a long line: someone remembered a small detail about their life and asked about it. That one moment carried them through a hard season."},
  {"type":"story","title":null,"text":"An elderly man, in the checkout line at a grocery store: someone simply said, \"I'm glad you're here\". No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A single father, on their hardest day in months: someone drove out of their way just to bring them home. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A soldier home on leave, on their hardest day in months: a fellow passenger gave up their seat with a kind word. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A tired commuter, on a cold winter evening: someone simply said, \"I'm glad you're here\". It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A retired teacher, on a rainy Tuesday morning: a coworker left a handwritten note of encouragement on their desk. That one moment carried them through a hard season."},
  {"type":"story","title":null,"text":"A coworker having a hard week, during finals week: someone sat down beside them and just listened. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A refugee family, on a quiet Sunday afternoon: someone let them go first in line with a warm smile. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A tired father, in a crowded train station: a coworker left a handwritten note of encouragement on their desk. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, in a waiting room: a stranger paid for their coffee and walked away before they could say thank you. It reminded them that people are still good."},
  {"type":"quote","text":"Just when the caterpillar thought the world was over, it became a butterfly.","source":"Unknown"},
  {"type":"quote","text":"Hardships often prepare ordinary people for an extraordinary destiny.","source":"C.S. Lewis"},
  {"type":"story","title":null,"text":"A shop owner, far from home for the holidays: someone let them go first in line with a warm smile. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A tired commuter, on the bus home from a hard shift: a child waved and said hello, like it was the easiest thing in the world. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"An elderly man, during a long hospital wait: someone paid off the balance on a stranger's layaway order. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A coworker having a hard week, just after losing a job: a stranger carried their bags up the stairs without being asked. It cost the giver nothing, and meant everything."},
  {"type":"quote","text":"Worry does not empty tomorrow of its sorrow, it empties today of its strength.","source":"Corrie ten Boom"},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, just before a hard appointment: someone paid off the balance on a stranger's layaway order. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A tired father, on their hardest day in months: someone sat down beside them and just listened. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A soldier home on leave, in a crowded train station: a passerby offered their umbrella without a word. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A struggling college student, in a crowded train station: someone simply said, \"I'm glad you're here\". For the first time in weeks, they felt seen."},
  {"type":"quote","text":"Kindness gives birth to kindness.","source":"Sophocles"},
  {"type":"story","title":null,"text":"A struggling college student, on their hardest day in months: someone drove out of their way just to bring them home. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A single father, in a waiting room: an anonymous gift appeared at their door that week. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A first-time volunteer, in a waiting room: an anonymous gift appeared at their door that week. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A soldier home on leave, during finals week: someone let them go first in line with a warm smile. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A young mother, on the bus home from a hard shift: someone let them go first in line with a warm smile. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, during a difficult week at work: someone drove out of their way just to bring them home. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A patient in a hospital bed, far from home for the holidays: someone remembered a small detail about their life and asked about it. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A retired teacher, after a sleepless night: a stranger's small joke made them laugh for the first time in days. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, after a sleepless night: someone simply said, \"I'm glad you're here\". It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A young intern, during a long hospital wait: a note was left in a library book that read, \"you are not alone\". It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A refugee family, on their hardest day in months: someone let them go first in line with a warm smile. That one moment carried them through a hard season."},
  {"type":"quote","text":"A good head and a good heart are always a formidable combination.","source":"Nelson Mandela"},
  {"type":"quote","text":"Never be afraid to trust an unknown future to a known God.","source":"Corrie ten Boom"},
  {"type":"story","title":null,"text":"A first-time volunteer, after a sleepless night: an anonymous gift appeared at their door that week. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A tired father, during finals week: a stranger carried their bags up the stairs without being asked. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A new student, on a cold winter evening: a stranger carried their bags up the stairs without being asked. That one moment carried them through a hard season."},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, on the anniversary of a loss: someone let them go first in line with a warm smile. It was a small thing. It changed their whole day."},
  {"type":"quote","text":"For every dark night, there's a brighter day.","source":"Tupac Shakur"},
  {"type":"story","title":null,"text":"A struggling college student, during finals week: a teacher stayed late just to tell them she believed in them. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, far from home for the holidays: a stranger carried their bags up the stairs without being asked. For the first time in weeks, they felt seen."},
  {"type":"quote","text":"It is not how much we give, but how much love we put into giving.","source":"Mother Teresa"},
  {"type":"quote","text":"Everything that irritates us about others can lead us to an understanding of ourselves.","source":"Carl Jung"},
  {"type":"story","title":null,"text":"A tired father, at the end of a long line: a note was left in a library book that read, \"you are not alone\". They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A retired teacher, during finals week: a coworker left a handwritten note of encouragement on their desk. They found themselves smiling the rest of the day."},
  {"type":"quote","text":"The smallest act of kindness is worth more than the grandest intention.","source":"Oscar Wilde"},
  {"type":"quote","text":"In the middle of every difficulty lies opportunity.","source":"Albert Einstein"},
  {"type":"story","title":null,"text":"A first-time volunteer, just after losing a job: a passerby offered their umbrella without a word. That one moment carried them through a hard season."},
  {"type":"story","title":null,"text":"A single father, just after losing a job: someone let them go first in line with a warm smile. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A grieving widow, on a quiet Sunday afternoon: a note was left in a library book that read, \"you are not alone\". It cost the giver nothing, and meant everything."},
  {"type":"quote","text":"God whispers to us in our pleasures... but shouts in our pains: it is his megaphone to rouse a deaf world.","source":"C.S. Lewis"},
  {"type":"story","title":null,"text":"A little girl, on their first day somewhere new: a neighbor left a meal on their doorstep, no note attached. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, during a long hospital wait: someone simply said, \"I'm glad you're here\". Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A coworker having a hard week, on a rainy Tuesday morning: a coworker covered their shift without being asked twice. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A quiet teenager, on the anniversary of a loss: an old friend called out of nowhere, just to check in. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, on their hardest day in months: a coworker left a handwritten note of encouragement on their desk. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A young intern, while sitting alone at lunch: someone paid off the balance on a stranger's layaway order. They passed the kindness on to someone else that same week."},
  {"type":"quote","text":"You never know how much your encouragement will mean to someone until you give it.","source":"Unknown"},
  {"type":"quote","text":"I have found that among its other benefits, giving liberates the soul of the giver.","source":"Maya Angelou"},
  {"type":"story","title":null,"text":"A new student, on their first day somewhere new: someone let them go first in line with a warm smile. It was enough to help them keep going."},
  {"type":"quote","text":"Life is not measured by the number of breaths we take, but by the moments that take our breath away.","source":"Attr. Maya Angelou"},
  {"type":"story","title":null,"text":"A young mother, just before a hard appointment: a passerby offered their umbrella without a word. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A stranger at the bus stop, just before a hard appointment: someone simply said, \"I'm glad you're here\". It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A patient in a hospital bed, on the anniversary of a loss: a stranger paid for their coffee and walked away before they could say thank you. They never forgot it."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, while sitting alone at lunch: a teacher stayed late just to tell them she believed in them. For the first time in weeks, they felt seen."},
  {"type":"quote","text":"Even the smallest act of caring for another person is like a drop of water — it will make ripples through the entire pond.","source":"Unknown"},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, on their first day somewhere new: someone sat down beside them and just listened. They passed the kindness on to someone else that same week."},
  {"type":"quote","text":"A little bit of encouragement goes further than a whole lot of criticism.","source":"Unknown"},
  {"type":"story","title":null,"text":"A shop owner, in a waiting room: a passerby offered their umbrella without a word. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, just after losing a job: someone remembered a small detail about their life and asked about it. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A shop owner, just after losing a job: someone simply said, \"I'm glad you're here\". Sometimes, that's all it takes."},
  {"type":"quote","text":"Carry out a random act of kindness, with no expectation of reward.","source":"Princess Diana"},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, during a difficult week at work: a stranger's small joke made them laugh for the first time in days. It cost the giver nothing, and meant everything."},
  {"type":"quote","text":"Do all the good you can, by all the means you can, in all the ways you can, to all the people you can, for as long as you can.","source":"Attr. John Wesley"},
  {"type":"story","title":null,"text":"A stranger at the bus stop, in a waiting room: a child waved and said hello, like it was the easiest thing in the world. It was enough to help them keep going."},
  {"type":"quote","text":"The best way to cheer yourself up is to try to cheer somebody else up.","source":"Mark Twain"},
  {"type":"quote","text":"Try to be a rainbow in someone's cloud.","source":"Maya Angelou"},
  {"type":"quote","text":"Never lose an opportunity of seeing anything that is beautiful.","source":"Ralph Waldo Emerson"},
  {"type":"quote","text":"Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'","source":"C.S. Lewis"},
  {"type":"story","title":null,"text":"A young intern, far from home for the holidays: a teacher stayed late just to tell them she believed in them. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A stranger at the bus stop, during a long hospital wait: someone complimented them, sincerely, for no particular reason. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A young intern, after a long, discouraging day: a note was left in a library book that read, \"you are not alone\". It was enough to help them keep going."},
  {"type":"story","title":null,"text":"An elderly man, on the anniversary of a loss: a child waved and said hello, like it was the easiest thing in the world. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, on their hardest day in months: someone let them go first in line with a warm smile. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A young intern, on a rainy Tuesday morning: a stranger's small joke made them laugh for the first time in days. For the first time in weeks, they felt seen."},
  {"type":"quote","text":"Joy is the simplest form of gratitude.","source":"Karl Barth"},
  {"type":"story","title":null,"text":"A tired father, on a rainy Tuesday morning: a coworker left a handwritten note of encouragement on their desk. Sometimes, that's all it takes."},
  {"type":"quote","text":"As we let our own light shine, we unconsciously give other people permission to do the same.","source":"Marianne Williamson"},
  {"type":"story","title":null,"text":"An elderly man, on a cold winter evening: someone paid off the balance on a stranger's layaway order. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, in a crowded train station: someone complimented them, sincerely, for no particular reason. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A grieving widow, on a cold winter evening: someone remembered a small detail about their life and asked about it. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, on a quiet Sunday afternoon: a child waved and said hello, like it was the easiest thing in the world. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A young mother, in the checkout line at a grocery store: a stranger carried their bags up the stairs without being asked. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A patient in a hospital bed, in the checkout line at a grocery store: a child waved and said hello, like it was the easiest thing in the world. That one moment carried them through a hard season."},
  {"type":"quote","text":"Small deeds done are better than great deeds planned.","source":"Peter Marshall"},
  {"type":"story","title":null,"text":"A coworker having a hard week, just after losing a job: a coworker left a handwritten note of encouragement on their desk. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A shop owner, while sitting alone at lunch: an anonymous gift appeared at their door that week. It reminded them that people are still good."},
  {"type":"quote","text":"Alone we can do so little; together we can do so much.","source":"Helen Keller"},
  {"type":"story","title":null,"text":"A quiet teenager, on the bus home from a hard shift: someone sat down beside them and just listened. They never forgot it."},
  {"type":"story","title":null,"text":"A first-time volunteer, in a waiting room: a fellow passenger gave up their seat with a kind word. It gave them the strength to face what came next."},
  {"type":"quote","text":"Where there is great love, there are always miracles.","source":"Willa Cather"},
  {"type":"story","title":null,"text":"A shop owner, while sitting alone at lunch: someone complimented them, sincerely, for no particular reason. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A new student, on a cold winter evening: an anonymous gift appeared at their door that week. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A quiet teenager, on their first day somewhere new: a coworker covered their shift without being asked twice. No one ever knew how much it mattered, except the one who received it."},
  {"type":"quote","text":"Although the world is full of suffering, it is also full of the overcoming of it.","source":"Helen Keller"},
  {"type":"story","title":null,"text":"A tired father, just after losing a job: an old friend called out of nowhere, just to check in. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A coworker having a hard week, at the end of a long line: a stranger carried their bags up the stairs without being asked. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A retired teacher, just after losing a job: a teacher stayed late just to tell them she believed in them. They passed the kindness on to someone else that same week."},
  {"type":"quote","text":"Every day may not be good, but there is something good in every day.","source":"Unknown"},
  {"type":"story","title":null,"text":"A stranger at the bus stop, while sitting alone at lunch: someone drove out of their way just to bring them home. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A retired teacher, on their hardest day in months: a stranger's small joke made them laugh for the first time in days. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A quiet teenager, on a quiet Sunday afternoon: a note was left in a library book that read, \"you are not alone\". It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A young intern, just after losing a job: a coworker left a handwritten note of encouragement on their desk. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A patient in a hospital bed, during a long hospital wait: someone drove out of their way just to bring them home. Sometimes, that's all it takes."},
  {"type":"quote","text":"The greatest thing in the world is to know how to belong to oneself, and still care for others.","source":"Attr. Michel de Montaigne"},
  {"type":"story","title":null,"text":"A soldier home on leave, after a long, discouraging day: an anonymous gift appeared at their door that week. That one moment carried them through a hard season."},
  {"type":"quote","text":"Sometimes the smallest step in the right direction ends up being the biggest step of your life.","source":"Unknown"},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, during a long hospital wait: a coworker covered their shift without being asked twice. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, on their hardest day in months: an anonymous gift appeared at their door that week. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A young intern, after a sleepless night: someone remembered a small detail about their life and asked about it. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, in a crowded train station: a passerby offered their umbrella without a word. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A coworker having a hard week, after a sleepless night: an old friend called out of nowhere, just to check in. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A tired commuter, on their first day somewhere new: a stranger paid for their coffee and walked away before they could say thank you. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A single father, at the end of a long line: a child waved and said hello, like it was the easiest thing in the world. Years later, they still told the story."},
  {"type":"quote","text":"People will forget what you said, people will forget what you did, but people will never forget how you made them feel.","source":"Maya Angelou"},
  {"type":"story","title":null,"text":"A grieving widow, on their first day somewhere new: someone paid off the balance on a stranger's layaway order. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, on the anniversary of a loss: someone sat down beside them and just listened. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A refugee family, on a quiet Sunday afternoon: an old friend called out of nowhere, just to check in. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A tired commuter, on a quiet Sunday afternoon: a teacher stayed late just to tell them she believed in them. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, during finals week: a stranger paid for their coffee and walked away before they could say thank you. That one moment carried them through a hard season."},
  {"type":"quote","text":"We must accept finite disappointment, but never lose infinite hope.","source":"Martin Luther King Jr."},
  {"type":"quote","text":"Once you choose hope, anything's possible.","source":"Christopher Reeve"},
  {"type":"quote","text":"A single sunbeam is enough to drive away many shadows.","source":"Francis of Assisi"},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, during a difficult week at work: someone simply said, \"I'm glad you're here\". Years later, they still told the story."},
  {"type":"story","title":null,"text":"A patient in a hospital bed, while sitting alone at lunch: a stranger paid for their coffee and walked away before they could say thank you. No one ever knew how much it mattered, except the one who received it."},
  {"type":"quote","text":"Gratitude turns what we have into enough.","source":"Unknown"},
  {"type":"story","title":null,"text":"A shop owner, on a rainy Tuesday morning: someone complimented them, sincerely, for no particular reason. Years later, they still told the story."},
  {"type":"story","title":null,"text":"An anxious traveler, on the anniversary of a loss: someone sat down beside them and just listened. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A stranger at the bus stop, during a long hospital wait: an anonymous gift appeared at their door that week. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"An anxious traveler, far from home for the holidays: a coworker left a handwritten note of encouragement on their desk. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A single father, after a long, discouraging day: a passerby offered their umbrella without a word. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A tired father, on a cold winter evening: a coworker covered their shift without being asked twice. They never forgot it."},
  {"type":"quote","text":"The greatest glory in living lies not in never falling, but in rising every time we fall.","source":"Nelson Mandela"},
  {"type":"quote","text":"Not all of us can do great things, but we can do small things with great love.","source":"Mother Teresa"},
  {"type":"story","title":null,"text":"A young mother, far from home for the holidays: someone let them go first in line with a warm smile. They never forgot it."},
  {"type":"story","title":null,"text":"A single father, while sitting alone at lunch: a child waved and said hello, like it was the easiest thing in the world. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A little girl, on the bus home from a hard shift: an old friend called out of nowhere, just to check in. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A stranger at the bus stop, on the anniversary of a loss: someone drove out of their way just to bring them home. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, while sitting alone at lunch: a neighbor left a meal on their doorstep, no note attached. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"An elderly man, on their first day somewhere new: a teacher stayed late just to tell them she believed in them. That one moment carried them through a hard season."},
  {"type":"quote","text":"Even the darkest night will end and the sun will rise.","source":"Victor Hugo"},
  {"type":"quote","text":"It is only with the heart that one can see rightly; what is essential is invisible to the eye.","source":"Antoine de Saint-Exupéry"},
  {"type":"story","title":null,"text":"An elderly man, just before a hard appointment: a teacher stayed late just to tell them she believed in them. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A quiet teenager, on a quiet Sunday afternoon: a coworker left a handwritten note of encouragement on their desk. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, in a waiting room: a note was left in a library book that read, \"you are not alone\". Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A quiet teenager, just before a hard appointment: a coworker covered their shift without being asked twice. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A grieving widow, in the checkout line at a grocery store: a note was left in a library book that read, \"you are not alone\". It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A new student, on the bus home from a hard shift: a fellow passenger gave up their seat with a kind word. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A stranger at the bus stop, on a quiet Sunday afternoon: a passerby offered their umbrella without a word. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A shop owner, during a long hospital wait: someone simply said, \"I'm glad you're here\". No one ever knew how much it mattered, except the one who received it."},
  {"type":"quote","text":"One kind word can warm three winter months.","source":"Japanese proverb"},
  {"type":"story","title":null,"text":"A little girl, during finals week: a note was left in a library book that read, \"you are not alone\". For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A struggling college student, after a long, discouraging day: someone paid off the balance on a stranger's layaway order. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A first-time volunteer, during a long hospital wait: a passerby offered their umbrella without a word. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A grieving widow, in the checkout line at a grocery store: a coworker left a handwritten note of encouragement on their desk. They passed the kindness on to someone else that same week."},
  {"type":"quote","text":"The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.","source":"Charles Dickens"},
  {"type":"quote","text":"In spite of everything, I still believe that people are really good at heart.","source":"Anne Frank"},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, in the checkout line at a grocery store: an old friend called out of nowhere, just to check in. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A refugee family, on a cold winter evening: a passerby offered their umbrella without a word. For the first time in weeks, they felt seen."},
  {"type":"quote","text":"Kindness is the language which the deaf can hear and the blind can see.","source":"Mark Twain"},
  {"type":"story","title":null,"text":"A stranger at the bus stop, in the checkout line at a grocery store: someone let them go first in line with a warm smile. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A tired commuter, on their hardest day in months: someone remembered a small detail about their life and asked about it. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A refugee family, in a crowded train station: an anonymous gift appeared at their door that week. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A patient in a hospital bed, just before a hard appointment: someone simply said, \"I'm glad you're here\". It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A coworker having a hard week, after a sleepless night: a neighbor left a meal on their doorstep, no note attached. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, just before a hard appointment: a coworker left a handwritten note of encouragement on their desk. They never forgot it."},
  {"type":"story","title":null,"text":"A quiet teenager, on their first day somewhere new: a stranger carried their bags up the stairs without being asked. It was a small thing. It changed their whole day."},
  {"type":"quote","text":"Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.","source":"Helen Keller"},
  {"type":"quote","text":"What lies behind us and what lies before us are tiny matters compared to what lies within us.","source":"Attr. Ralph Waldo Emerson"},
  {"type":"story","title":null,"text":"A patient in a hospital bed, in a waiting room: a child waved and said hello, like it was the easiest thing in the world. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A first-time volunteer, after a long, discouraging day: a coworker covered their shift without being asked twice. For the first time in weeks, they felt seen."},
  {"type":"quote","text":"Peace begins with a smile.","source":"Mother Teresa"},
  {"type":"quote","text":"Life's most persistent and urgent question is: what are you doing for others?","source":"Martin Luther King Jr."},
  {"type":"story","title":null,"text":"A little girl, during a difficult week at work: someone sat down beside them and just listened. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A struggling college student, on their hardest day in months: a stranger paid for their coffee and walked away before they could say thank you. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A grieving widow, in a crowded train station: a stranger's small joke made them laugh for the first time in days. It reminded them that people are still good."},
  {"type":"quote","text":"No one has ever become poor by giving.","source":"Anne Frank"},
  {"type":"quote","text":"Kind words can be short and easy to speak, but their echoes are truly endless.","source":"Mother Teresa"},
  {"type":"story","title":null,"text":"A young mother, during a long hospital wait: an old friend called out of nowhere, just to check in. They found themselves smiling the rest of the day."},
  {"type":"quote","text":"No act of kindness, no matter how small, is ever wasted.","source":"Aesop"},
  {"type":"quote","text":"The greatest gift you can give someone is your presence.","source":"Thich Nhat Hanh"},
  {"type":"story","title":null,"text":"A patient in a hospital bed, just after losing a job: someone drove out of their way just to bring them home. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A tired father, on a quiet Sunday afternoon: a neighbor left a meal on their doorstep, no note attached. It was enough to help them keep going."},
  {"type":"quote","text":"Look for the helpers. You will always find people who are helping.","source":"Fred Rogers"},
  {"type":"quote","text":"A warm smile is the universal language of kindness.","source":"Unknown"},
  {"type":"story","title":null,"text":"An anxious traveler, in a waiting room: a teacher stayed late just to tell them she believed in them. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A soldier home on leave, just after losing a job: a stranger carried their bags up the stairs without being asked. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A little girl, on their first day somewhere new: someone sat down beside them and just listened. It cost the giver nothing, and meant everything."},
  {"type":"quote","text":"Be the reason someone believes in the goodness of people.","source":"Unknown"},
  {"type":"story","title":null,"text":"A refugee family, at the end of a long line: an anonymous gift appeared at their door that week. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, far from home for the holidays: a child waved and said hello, like it was the easiest thing in the world. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, at the end of a long line: a teacher stayed late just to tell them she believed in them. They never forgot it."},
  {"type":"story","title":null,"text":"A young mother, on their first day somewhere new: a coworker covered their shift without being asked twice. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, after a long, discouraging day: someone complimented them, sincerely, for no particular reason. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A retired teacher, at the end of a long line: a note was left in a library book that read, \"you are not alone\". For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"An elderly man, just before a hard appointment: someone drove out of their way just to bring them home. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A refugee family, during finals week: a coworker covered their shift without being asked twice. They never forgot it."},
  {"type":"story","title":null,"text":"A refugee family, in a crowded train station: a stranger carried their bags up the stairs without being asked. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, on a cold winter evening: a note was left in a library book that read, \"you are not alone\". Years later, they still told the story."},
  {"type":"story","title":null,"text":"A retired teacher, after a long, discouraging day: someone sat down beside them and just listened. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, after a sleepless night: a note was left in a library book that read, \"you are not alone\". It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A young mother, while sitting alone at lunch: an anonymous gift appeared at their door that week. Years later, they still told the story."},
  {"type":"quote","text":"When it is darkest, we can see the stars.","source":"Ralph Waldo Emerson"},
  {"type":"story","title":null,"text":"A patient in a hospital bed, just before a hard appointment: someone remembered a small detail about their life and asked about it. It cost the giver nothing, and meant everything."},
  {"type":"quote","text":"You give but little when you give of your possessions. It is when you give of yourself that you truly give.","source":"Kahlil Gibran"},
  {"type":"story","title":null,"text":"A refugee family, on a cold winter evening: a coworker covered their shift without being asked twice. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A tired commuter, on their hardest day in months: a teacher stayed late just to tell them she believed in them. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"An elderly man, on the bus home from a hard shift: a stranger paid for their coffee and walked away before they could say thank you. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A new student, in a crowded train station: an old friend called out of nowhere, just to check in. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, on a rainy Tuesday morning: someone drove out of their way just to bring them home. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, on the bus home from a hard shift: someone drove out of their way just to bring them home. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"A patient in a hospital bed, during a long hospital wait: a teacher stayed late just to tell them she believed in them. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A refugee family, during a difficult week at work: a fellow passenger gave up their seat with a kind word. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A first-time volunteer, just after losing a job: someone let them go first in line with a warm smile. Years later, they still told the story."},
  {"type":"quote","text":"When you have nothing left but God, you become aware that God is enough.","source":"Attr. Corrie ten Boom"},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, during finals week: a teacher stayed late just to tell them she believed in them. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, after a sleepless night: someone paid off the balance on a stranger's layaway order. Years later, they still told the story."},
  {"type":"story","title":null,"text":"An anxious traveler, in the checkout line at a grocery store: a teacher stayed late just to tell them she believed in them. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A man sleeping rough that winter, after a long, discouraging day: someone simply said, \"I'm glad you're here\". It was a small thing. It changed their whole day."},
  {"type":"quote","text":"Hope is being able to see that there is light despite all of the darkness.","source":"Desmond Tutu"},
  {"type":"story","title":null,"text":"A struggling college student, during finals week: someone remembered a small detail about their life and asked about it. That one moment carried them through a hard season."},
  {"type":"story","title":null,"text":"A tired commuter, in a crowded train station: someone paid off the balance on a stranger's layaway order. That one moment carried them through a hard season."},
  {"type":"story","title":null,"text":"A little girl, on a cold winter evening: a coworker left a handwritten note of encouragement on their desk. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A new student, on a quiet Sunday afternoon: a passerby offered their umbrella without a word. It was the encouragement they didn't know they needed."},
  {"type":"quote","text":"Be kind, for everyone you meet is fighting a hard battle.","source":"Attr. Ian Maclaren"},
  {"type":"story","title":null,"text":"A grieving widow, during a difficult week at work: a coworker left a handwritten note of encouragement on their desk. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A retired teacher, far from home for the holidays: someone sat down beside them and just listened. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A single father, during finals week: an anonymous gift appeared at their door that week. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"An elderly man, in the checkout line at a grocery store: someone remembered a small detail about their life and asked about it. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A young mother, in a waiting room: a coworker covered their shift without being asked twice. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A struggling college student, during a difficult week at work: someone paid off the balance on a stranger's layaway order. Sometimes, that's all it takes."},
  {"type":"story","title":null,"text":"A little girl, on a quiet Sunday afternoon: a coworker covered their shift without being asked twice. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, during a difficult week at work: someone complimented them, sincerely, for no particular reason. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A tired commuter, during finals week: a child waved and said hello, like it was the easiest thing in the world. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A soldier home on leave, at the end of a long line: a coworker covered their shift without being asked twice. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A little girl, on a quiet Sunday afternoon: a stranger carried their bags up the stairs without being asked. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A little girl, on their hardest day in months: a stranger carried their bags up the stairs without being asked. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A refugee family, on their first day somewhere new: a fellow passenger gave up their seat with a kind word. Years later, they still told the story."},
  {"type":"story","title":null,"text":"An anxious traveler, while sitting alone at lunch: someone sat down beside them and just listened. It's a small story, but it's one worth telling."},
  {"type":"quote","text":"Encouragement is oxygen to the soul.","source":"Unknown"},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, on a cold winter evening: a passerby offered their umbrella without a word. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A first-time volunteer, on a rainy Tuesday morning: an old friend called out of nowhere, just to check in. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A stranger at the bus stop, on the bus home from a hard shift: an anonymous gift appeared at their door that week. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, during finals week: a child waved and said hello, like it was the easiest thing in the world. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A new student, on the anniversary of a loss: a stranger carried their bags up the stairs without being asked. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A shop owner, during a long hospital wait: a child waved and said hello, like it was the easiest thing in the world. It was a small thing. It changed their whole day."},
  {"type":"story","title":null,"text":"A quiet teenager, on the bus home from a hard shift: a neighbor left a meal on their doorstep, no note attached. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A soldier home on leave, after a sleepless night: an old friend called out of nowhere, just to check in. They never forgot it."},
  {"type":"story","title":null,"text":"A grieving widow, on the anniversary of a loss: a teacher stayed late just to tell them she believed in them. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A retired teacher, at the end of a long line: a teacher stayed late just to tell them she believed in them. It cost the giver nothing, and meant everything."},
  {"type":"quote","text":"Three things in human life are important: the first is to be kind; the second is to be kind; and the third is to be kind.","source":"Henry James"},
  {"type":"story","title":null,"text":"A tired father, after a long, discouraging day: a neighbor left a meal on their doorstep, no note attached. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A shop owner, in a waiting room: someone drove out of their way just to bring them home. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A tired commuter, during a difficult week at work: someone drove out of their way just to bring them home. They never forgot it."},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, just after losing a job: someone sat down beside them and just listened. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A little girl, in a crowded train station: an old friend called out of nowhere, just to check in. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A first-time volunteer, far from home for the holidays: a stranger carried their bags up the stairs without being asked. They never forgot it."},
  {"type":"story","title":null,"text":"A young intern, just before a hard appointment: someone remembered a small detail about their life and asked about it. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A shop owner, just before a hard appointment: someone let them go first in line with a warm smile. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A struggling college student, at the end of a long line: a child waved and said hello, like it was the easiest thing in the world. They never forgot it."},
  {"type":"quote","text":"You don't have to see the whole staircase, just take the first step.","source":"Attr. Martin Luther King Jr."},
  {"type":"story","title":null,"text":"A tired commuter, on the anniversary of a loss: someone remembered a small detail about their life and asked about it. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A first-time volunteer, far from home for the holidays: a coworker covered their shift without being asked twice. They found themselves smiling the rest of the day."},
  {"type":"quote","text":"Every act of love and kindness leaves this world a little better than it found it.","source":"Unknown"},
  {"type":"quote","text":"Encouragement costs nothing to give, but it is worth everything to receive.","source":"Unknown"},
  {"type":"story","title":null,"text":"A nurse finishing a night shift, in the checkout line at a grocery store: someone simply said, \"I'm glad you're here\". It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A young mother, in a waiting room: a stranger carried their bags up the stairs without being asked. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"A grieving widow, on the bus home from a hard shift: someone sat down beside them and just listened. Years later, they still told the story."},
  {"type":"story","title":null,"text":"An anxious traveler, in the checkout line at a grocery store: someone remembered a small detail about their life and asked about it. They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A tired father, after a sleepless night: a coworker covered their shift without being asked twice. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A new student, in the checkout line at a grocery store: a passerby offered their umbrella without a word. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A quiet teenager, during a long hospital wait: a neighbor left a meal on their doorstep, no note attached. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"A grieving widow, on the anniversary of a loss: someone remembered a small detail about their life and asked about it. It was the encouragement they didn't know they needed."},
  {"type":"story","title":null,"text":"An anxious traveler, on the anniversary of a loss: a stranger's small joke made them laugh for the first time in days. It gave them the strength to face what came next."},
  {"type":"quote","text":"A candle loses nothing by lighting another candle.","source":"Attr. James Keller"},
  {"type":"quote","text":"We rise by lifting others.","source":"Robert Ingersoll"},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, on a quiet Sunday afternoon: someone paid off the balance on a stranger's layaway order. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, after a sleepless night: a coworker left a handwritten note of encouragement on their desk. No one ever knew how much it mattered, except the one who received it."},
  {"type":"quote","text":"There is no exercise better for the heart than reaching down and lifting people up.","source":"Attr. John Andrew Holmes"},
  {"type":"quote","text":"Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.","source":"Martin Luther King Jr."},
  {"type":"story","title":null,"text":"An anxious traveler, on the bus home from a hard shift: a coworker left a handwritten note of encouragement on their desk. Years later, they still told the story."},
  {"type":"story","title":null,"text":"A young mother, on the anniversary of a loss: a fellow passenger gave up their seat with a kind word. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, in a crowded train station: someone let them go first in line with a warm smile. It gave them the strength to face what came next."},
  {"type":"story","title":null,"text":"A coworker having a hard week, far from home for the holidays: a note was left in a library book that read, \"you are not alone\". It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A single father, after a sleepless night: someone complimented them, sincerely, for no particular reason. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A retired teacher, after a sleepless night: someone paid off the balance on a stranger's layaway order. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A coworker having a hard week, in a waiting room: a neighbor left a meal on their doorstep, no note attached. They never forgot it."},
  {"type":"story","title":null,"text":"An overwhelmed waiter, at the end of a long line: a passerby offered their umbrella without a word. It was enough to help them keep going."},
  {"type":"quote","text":"What we do for ourselves dies with us. What we do for others and the world remains and is immortal.","source":"Albert Pike"},
  {"type":"story","title":null,"text":"A retired teacher, after a long, discouraging day: someone remembered a small detail about their life and asked about it. It's a small story, but it's one worth telling."},
  {"type":"story","title":null,"text":"An anxious traveler, on the bus home from a hard shift: someone paid off the balance on a stranger's layaway order. It was enough to help them keep going."},
  {"type":"story","title":null,"text":"A new student, during a long hospital wait: an anonymous gift appeared at their door that week. They never forgot it."},
  {"type":"quote","text":"Tough times never last, but tough people do.","source":"Robert H. Schuller"},
  {"type":"quote","text":"Hope is the thing with feathers that perches in the soul.","source":"Emily Dickinson"},
  {"type":"quote","text":"The world is full of nice people. If you can't find one, be one.","source":"Unknown"},
  {"type":"story","title":null,"text":"A single father, far from home for the holidays: someone drove out of their way just to bring them home. It was a small thing. It changed their whole day."},
  {"type":"quote","text":"This too shall pass.","source":"Persian proverb"},
  {"type":"story","title":null,"text":"A soldier home on leave, far from home for the holidays: a fellow passenger gave up their seat with a kind word. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A young intern, at the end of a long line: someone paid off the balance on a stranger's layaway order. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A quiet teenager, in the checkout line at a grocery store: a coworker left a handwritten note of encouragement on their desk. It cost the giver nothing, and meant everything."},
  {"type":"story","title":null,"text":"A single father, during a difficult week at work: someone let them go first in line with a warm smile. No one ever knew how much it mattered, except the one who received it."},
  {"type":"story","title":null,"text":"A young mother, just after losing a job: a fellow passenger gave up their seat with a kind word. That one moment carried them through a hard season."},
  {"type":"quote","text":"Where there is love and encouragement, there is always hope for a new day.","source":"Unknown"},
  {"type":"story","title":null,"text":"An overwhelmed waiter, on their hardest day in months: someone simply said, \"I'm glad you're here\". They passed the kindness on to someone else that same week."},
  {"type":"story","title":null,"text":"A struggling college student, at the end of a long line: someone simply said, \"I'm glad you're here\". They found themselves smiling the rest of the day."},
  {"type":"quote","text":"It always seems impossible until it's done.","source":"Nelson Mandela"},
  {"type":"story","title":null,"text":"A boy who never spoke up in class, just after losing a job: a coworker covered their shift without being asked twice. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A patient in a hospital bed, in the checkout line at a grocery store: someone paid off the balance on a stranger's layaway order. For the first time in weeks, they felt seen."},
  {"type":"story","title":null,"text":"An anxious traveler, just before a hard appointment: a note was left in a library book that read, \"you are not alone\". That one moment carried them through a hard season."},
  {"type":"quote","text":"A joyful heart is good medicine.","source":"Proverbs 17:22, paraphrase"},
  {"type":"story","title":null,"text":"A stranger at the bus stop, while sitting alone at lunch: a passerby offered their umbrella without a word. It reminded them that people are still good."},
  {"type":"story","title":null,"text":"A coworker having a hard week, after a long, discouraging day: a note was left in a library book that read, \"you are not alone\". They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A widow spending her first holiday alone, in a crowded train station: someone remembered a small detail about their life and asked about it. They found themselves smiling the rest of the day."},
  {"type":"story","title":null,"text":"A young intern, in a waiting room: someone sat down beside them and just listened. That one moment carried them through a hard season."},
  {"type":"story","title":null,"text":"An elderly man, in a crowded train station: someone drove out of their way just to bring them home. Years later, they still told the story."},
  {"type":"quote","text":"Kindness is a language which the deaf can hear and the blind can see.","source":"Mark Twain"},
  {"type":"quote","text":"A word of encouragement during a failure is worth more than an hour of praise after success.","source":"Unknown"},
];
