// 91 quotes on the power of encouragement and hope, drawn from a
// per-user shuffle of this bank (see pickForDaySmallBank in ../content) so
// the sequence never repeats an entry within 91 days of its last showing.
//
// This file used to also hold ~275 short fictional "vignette" entries
// (type: "story") mixed in alongside the quotes -- a mad-libs-style
// template ("[person], [situation]: [act]. [outcome].") that produced heavy
// phrase-level repetition once there were enough of them. They were dropped
// from a byLang.js filter to type === "quote" only a while back in favor of
// stories.js's verified true stories, and were never actually shown to a
// user again after that -- removed here since they were pure dead weight.

const WISDOM = [
  {"type":"quote","text":"Wherever there is a human being, there is an opportunity for a kindness.","source":"Seneca"},
  {"type":"quote","text":"A hedge between keeps friendship green.","source":"Proverb"},
  {"type":"quote","text":"The soul would have no rainbow had the eyes no tears.","source":"John Vance Cheney"},
  {"type":"quote","text":"A single act of kindness throws out roots in all directions, and the roots spring up and make new trees.","source":"Amelia Earhart"},
  {"type":"quote","text":"Every saint has a past, and every sinner has a future.","source":"Oscar Wilde"},
  {"type":"quote","text":"Hope begins in the dark, the stubborn hope that if you just show up and try to do the right thing, the dawn will come.","source":"Anne Lamott"},
  {"type":"quote","text":"The soul is healed by being with children.","source":"Fyodor Dostoevsky"},
  {"type":"quote","text":"How wonderful it is that nobody need wait a single moment before starting to improve the world.","source":"Anne Frank"},
  {"type":"quote","text":"Start each day with a grateful heart.","source":"Unknown"},
  {"type":"quote","text":"Faith is taking the first step even when you don't see the whole staircase.","source":"Martin Luther King Jr."},
  {"type":"quote","text":"The best portion of a good person's life: their little, nameless, unremembered acts of kindness and love.","source":"William Wordsworth"},
  {"type":"quote","text":"Just when the caterpillar thought the world was over, it became a butterfly.","source":"Unknown"},
  {"type":"quote","text":"Hardships often prepare ordinary people for an extraordinary destiny.","source":"C.S. Lewis"},
  {"type":"quote","text":"Worry does not empty tomorrow of its sorrow, it empties today of its strength.","source":"Corrie ten Boom"},
  {"type":"quote","text":"Kindness gives birth to kindness.","source":"Sophocles"},
  {"type":"quote","text":"A good head and a good heart are always a formidable combination.","source":"Nelson Mandela"},
  {"type":"quote","text":"Never be afraid to trust an unknown future to a known God.","source":"Corrie ten Boom"},
  {"type":"quote","text":"For every dark night, there's a brighter day.","source":"Tupac Shakur"},
  {"type":"quote","text":"It is not how much we give, but how much love we put into giving.","source":"Mother Teresa"},
  {"type":"quote","text":"Everything that irritates us about others can lead us to an understanding of ourselves.","source":"Carl Jung"},
  {"type":"quote","text":"The smallest act of kindness is worth more than the grandest intention.","source":"Oscar Wilde"},
  {"type":"quote","text":"In the middle of every difficulty lies opportunity.","source":"Albert Einstein"},
  {"type":"quote","text":"God whispers to us in our pleasures... but shouts in our pains: it is his megaphone to rouse a deaf world.","source":"C.S. Lewis"},
  {"type":"quote","text":"You never know how much your encouragement will mean to someone until you give it.","source":"Unknown"},
  {"type":"quote","text":"I have found that among its other benefits, giving liberates the soul of the giver.","source":"Maya Angelou"},
  {"type":"quote","text":"Life is not measured by the number of breaths we take, but by the moments that take our breath away.","source":"Attr. Maya Angelou"},
  {"type":"quote","text":"Even the smallest act of caring for another person is like a drop of water — it will make ripples through the entire pond.","source":"Unknown"},
  {"type":"quote","text":"A little bit of encouragement goes further than a whole lot of criticism.","source":"Unknown"},
  {"type":"quote","text":"Carry out a random act of kindness, with no expectation of reward.","source":"Princess Diana"},
  {"type":"quote","text":"Do all the good you can, by all the means you can, in all the ways you can, to all the people you can, for as long as you can.","source":"Attr. John Wesley"},
  {"type":"quote","text":"The best way to cheer yourself up is to try to cheer somebody else up.","source":"Mark Twain"},
  {"type":"quote","text":"Try to be a rainbow in someone's cloud.","source":"Maya Angelou"},
  {"type":"quote","text":"Never lose an opportunity of seeing anything that is beautiful.","source":"Ralph Waldo Emerson"},
  {"type":"quote","text":"Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'","source":"C.S. Lewis"},
  {"type":"quote","text":"Joy is the simplest form of gratitude.","source":"Karl Barth"},
  {"type":"quote","text":"As we let our own light shine, we unconsciously give other people permission to do the same.","source":"Marianne Williamson"},
  {"type":"quote","text":"Small deeds done are better than great deeds planned.","source":"Peter Marshall"},
  {"type":"quote","text":"Alone we can do so little; together we can do so much.","source":"Helen Keller"},
  {"type":"quote","text":"Where there is great love, there are always miracles.","source":"Willa Cather"},
  {"type":"quote","text":"Although the world is full of suffering, it is also full of the overcoming of it.","source":"Helen Keller"},
  {"type":"quote","text":"Every day may not be good, but there is something good in every day.","source":"Unknown"},
  {"type":"quote","text":"The greatest thing in the world is to know how to belong to oneself, and still care for others.","source":"Attr. Michel de Montaigne"},
  {"type":"quote","text":"Sometimes the smallest step in the right direction ends up being the biggest step of your life.","source":"Unknown"},
  {"type":"quote","text":"People will forget what you said, people will forget what you did, but people will never forget how you made them feel.","source":"Maya Angelou"},
  {"type":"quote","text":"We must accept finite disappointment, but never lose infinite hope.","source":"Martin Luther King Jr."},
  {"type":"quote","text":"Once you choose hope, anything's possible.","source":"Christopher Reeve"},
  {"type":"quote","text":"A single sunbeam is enough to drive away many shadows.","source":"Francis of Assisi"},
  {"type":"quote","text":"Gratitude turns what we have into enough.","source":"Unknown"},
  {"type":"quote","text":"The greatest glory in living lies not in never falling, but in rising every time we fall.","source":"Nelson Mandela"},
  {"type":"quote","text":"Not all of us can do great things, but we can do small things with great love.","source":"Mother Teresa"},
  {"type":"quote","text":"Even the darkest night will end and the sun will rise.","source":"Victor Hugo"},
  {"type":"quote","text":"It is only with the heart that one can see rightly; what is essential is invisible to the eye.","source":"Antoine de Saint-Exupéry"},
  {"type":"quote","text":"One kind word can warm three winter months.","source":"Japanese proverb"},
  {"type":"quote","text":"The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.","source":"Charles Dickens"},
  {"type":"quote","text":"In spite of everything, I still believe that people are really good at heart.","source":"Anne Frank"},
  {"type":"quote","text":"Kindness is the language which the deaf can hear and the blind can see.","source":"Mark Twain"},
  {"type":"quote","text":"Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.","source":"Helen Keller"},
  {"type":"quote","text":"What lies behind us and what lies before us are tiny matters compared to what lies within us.","source":"Attr. Ralph Waldo Emerson"},
  {"type":"quote","text":"Peace begins with a smile.","source":"Mother Teresa"},
  {"type":"quote","text":"Life's most persistent and urgent question is: what are you doing for others?","source":"Martin Luther King Jr."},
  {"type":"quote","text":"No one has ever become poor by giving.","source":"Anne Frank"},
  {"type":"quote","text":"Kind words can be short and easy to speak, but their echoes are truly endless.","source":"Mother Teresa"},
  {"type":"quote","text":"No act of kindness, no matter how small, is ever wasted.","source":"Aesop"},
  {"type":"quote","text":"The greatest gift you can give someone is your presence.","source":"Thich Nhat Hanh"},
  {"type":"quote","text":"Look for the helpers. You will always find people who are helping.","source":"Fred Rogers"},
  {"type":"quote","text":"A warm smile is the universal language of kindness.","source":"Unknown"},
  {"type":"quote","text":"Be the reason someone believes in the goodness of people.","source":"Unknown"},
  {"type":"quote","text":"When it is darkest, we can see the stars.","source":"Ralph Waldo Emerson"},
  {"type":"quote","text":"You give but little when you give of your possessions. It is when you give of yourself that you truly give.","source":"Kahlil Gibran"},
  {"type":"quote","text":"When you have nothing left but God, you become aware that God is enough.","source":"Attr. Corrie ten Boom"},
  {"type":"quote","text":"Hope is being able to see that there is light despite all of the darkness.","source":"Desmond Tutu"},
  {"type":"quote","text":"Be kind, for everyone you meet is fighting a hard battle.","source":"Attr. Ian Maclaren"},
  {"type":"quote","text":"Encouragement is oxygen to the soul.","source":"Unknown"},
  {"type":"quote","text":"Three things in human life are important: the first is to be kind; the second is to be kind; and the third is to be kind.","source":"Henry James"},
  {"type":"quote","text":"It's not what you look at that matters, it's what you see.","source":"Henry David Thoreau"},
  {"type":"quote","text":"Every act of love and kindness leaves this world a little better than it found it.","source":"Unknown"},
  {"type":"quote","text":"Encouragement costs nothing to give, but it is worth everything to receive.","source":"Unknown"},
  {"type":"quote","text":"A candle loses nothing by lighting another candle.","source":"Attr. James Keller"},
  {"type":"quote","text":"We rise by lifting others.","source":"Robert Ingersoll"},
  {"type":"quote","text":"There is no exercise better for the heart than reaching down and lifting people up.","source":"Attr. John Andrew Holmes"},
  {"type":"quote","text":"Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.","source":"Martin Luther King Jr."},
  {"type":"quote","text":"What we do for ourselves dies with us. What we do for others and the world remains and is immortal.","source":"Albert Pike"},
  {"type":"quote","text":"Tough times never last, but tough people do.","source":"Robert H. Schuller"},
  {"type":"quote","text":"Hope is the thing with feathers that perches in the soul.","source":"Emily Dickinson"},
  {"type":"quote","text":"The world is full of nice people. If you can't find one, be one.","source":"Unknown"},
  {"type":"quote","text":"This too shall pass.","source":"Persian proverb"},
  {"type":"quote","text":"Where there is love and encouragement, there is always hope for a new day.","source":"Unknown"},
  {"type":"quote","text":"It always seems impossible until it's done.","source":"Nelson Mandela"},
  {"type":"quote","text":"A joyful heart is good medicine.","source":"Proverbs 17:22, paraphrase"},
  {"type":"quote","text":"The greatest use of a life is to spend it on something that will outlast it.","source":"William James"},
  {"type":"quote","text":"A word of encouragement during a failure is worth more than an hour of praise after success.","source":"Unknown"},
];
