// 366 suggested "Barnabas moment" acts of kindness — one for every day of
// the year, including a leap day, with no repeats.
//
// Written to work for anyone, anywhere, regardless of age, relationship
// status, family situation, or living arrangement — a handful of targets
// that once assumed something about the reader (a spouse, kids of their
// own, a roommate) now carry a built-in alternative right in the phrase
// (e.g. "your partner (or the person closest to your heart)") instead of
// quietly excluding whoever that assumption doesn't fit. The moments span
// home, work, school, faith, neighborhood, and online life, and include
// gift-giving, introducing people to each other, and other ways to help
// someone feel valued, included, and seen — not just direct one-on-one
// kindness.

const BARNABAS_MOMENTS = [
  "Thank someone you live with (or a close friend, if you live alone) for something you don't usually say thank you for.",
  "Compliment the effort a mentor from your past is putting in, not just what they achieved.",
  "Give money, time, or goods to a cause someone close to you cares about, in their honor.",
  "Tell a mentor from your past exactly what makes them valuable to the people around them, not just what they do.",
  "Share something hopeful with a nurse or doctor you know — they might need it today.",
  "If you're able, quietly cover a small cost for your parent (or an elder in your life, or someone close to you) today — a coffee, a fare, a few dollars — without making it a big deal.",
  "Do a small task for a delivery driver without being asked.",
  "Recommend your pastor or a spiritual leader for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Tell a coworker having a rough week how they've shaped who you are.",
  "Tell someone whose work usually goes unnoticed how they've shaped who you are.",
  "Really listen to someone teaching themselves something hard right now today, without planning what you'll say next.",
  "Do a small task for a coworker having a rough week without being asked.",
  "Celebrate a win your sibling (or someone who feels like one) had today — say it out loud.",
  "Compliment the effort a first responder is putting in, not just what they achieved.",
  "Give a child in your life your full attention for five minutes today, phone away.",
  "Check in on someone who helped you once just to see how they're really doing.",
  "Do a small task for someone who looks worn out without being asked.",
  "Give away something you own but rarely use to someone who could actually use it.",
  "Tell someone teaching themselves something hard right now how they've shaped who you are.",
  "Include a family member in something today — a meal, a plan, a conversation — so they know they belong.",
  "Ask someone going through a hard season how they're really doing, and wait for the real answer.",
  "Check in on someone you disagreed with recently just to see how they're really doing.",
  "Tell a first responder one specific thing you admire about them.",
  "Write someone you disagreed with recently a short note of encouragement and leave it where they'll find it.",
  "Tell a close friend exactly what makes them valuable to the people around them, not just what they do.",
  "Ask a new coworker or classmate what would make today easier for them, then help make it happen.",
  "Do something small just for yourself today — no reason needed, no one else has to know.",
  "Ask a classmate how they're really doing, and wait for the real answer.",
  "Take real notice of a first responder today — thank them and ask how they're really doing.",
  "Recommend someone in your community for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Celebrate a win you had today, even a small one — say it out loud, the way you would for someone else.",
  "Ask a family member how they're really doing, and wait for the real answer.",
  "Let a service worker know you're thinking of them, unprompted.",
  "Send a close friend a message telling them exactly why you're grateful for them.",
  "Give an old friend you've lost touch with a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Recommend a teacher for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Say something good about someone new to your city to someone else today — the kind of thing that has a way of getting back to people.",
  "Tell someone in your community how they've shaped who you are.",
  "Give a delivery driver a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Share something hopeful with an old friend you've lost touch with — they might need it today.",
  "Tell a parent you know one specific thing you admire about them.",
  "Tell a small business owner nearby one specific thing you admire about them.",
  "Celebrate a win a parent you know had today — say it out loud.",
  "Say a genuine 'well done' to someone doing a job most people walk past without noticing.",
  "Tell someone in your household three things you appreciate about them today, one at a time.",
  "Look at yourself in the mirror today and say thank you — for showing up, for not giving up, for still trying.",
  "Thank your partner (or the person closest to your heart) for something you don't usually say thank you for.",
  "Thank someone whose work usually goes unnoticed for something you don't usually say thank you for.",
  "Write a letter — an actual paper letter — to someone who would never expect one.",
  "Tell a teacher how they've shaped who you are.",
  "Really listen to someone sitting alone today, without planning what you'll say next.",
  "If you're able, quietly cover a small cost for your pastor or a spiritual leader today — a coffee, a fare, a few dollars — without making it a big deal.",
  "Tell someone teaching themselves something hard right now exactly what makes them valuable to the people around them, not just what they do.",
  "Do a small task for your local barista or cashier without being asked.",
  "Let a teacher know you're thinking of them, unprompted.",
  "Check in on a coworker having a rough week just to see how they're really doing.",
  "Ask a small business owner nearby how they're really doing, and wait for the real answer.",
  "Tell a neighbor exactly what makes them valuable to the people around them, not just what they do.",
  "Ask a caregiver what would make today easier for them, then help make it happen.",
  "Send someone sitting alone a message telling them exactly why you're grateful for them.",
  "Tell a caregiver exactly what makes them valuable to the people around them, not just what they do.",
  "Give up your seat, your place in line, or your turn for someone today, cheerfully.",
  "Give someone whose work usually goes unnoticed your full attention for five minutes today, phone away.",
  "Celebrate a win a new coworker or classmate had today — say it out loud.",
  "Tell an old friend you've lost touch with how they've shaped who you are.",
  "Ask a parent you know how they're really doing, and wait for the real answer.",
  "Compliment the effort a caregiver is putting in, not just what they achieved.",
  "Give a first responder a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Tell someone quietly struggling how they've shaped who you are.",
  "Tell an online friend how they've shaped who you are.",
  "Write your pastor or a spiritual leader a short note of encouragement and leave it where they'll find it.",
  "Ask a coworker how they're really doing, and wait for the real answer.",
  "Recommend an old friend you've lost touch with for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Leave a generous tip today for someone in a service job, if you're able, and let them see you mean it.",
  "Do the one necessary thing you've been putting off today — the relief afterward is the gift.",
  "Include an online friend in something today — a meal, a plan, a conversation — so they know they belong.",
  "If you're able, quietly cover a small cost for a new coworker or classmate today — a coffee, a fare, a few dollars — without making it a big deal.",
  "Do a small task for an online friend without being asked.",
  "Ask your sibling (or someone who feels like one) how they're really doing, and wait for the real answer.",
  "Include someone sitting alone in something today — a meal, a plan, a conversation — so they know they belong.",
  "Thank a teacher for something you don't usually say thank you for.",
  "Give someone who looks worn out a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Give someone you live with (or a close friend, if you live alone) a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Share something hopeful with a teacher — they might need it today.",
  "Ask a teacher what would make today easier for them, then help make it happen.",
  "Recommend a first responder for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Bring your local barista or cashier something small — a coffee, a snack, a kind word.",
  "Compliment the effort a new coworker or classmate is putting in, not just what they achieved.",
  "Really listen to someone whose work usually goes unnoticed today, without planning what you'll say next.",
  "Include a coworker in something today — a meal, a plan, a conversation — so they know they belong.",
  "If you're able, quietly cover a small cost for someone sitting alone today — a coffee, a fare, a few dollars — without making it a big deal.",
  "Introduce two people in your life who don't know each other yet but who you think would genuinely get along or help each other.",
  "Compliment the effort someone new is putting in, not just what they achieved.",
  "Tell a parent you know exactly what makes them valuable to the people around them, not just what they do.",
  "Include someone teaching themselves something hard right now in something today — a meal, a plan, a conversation — so they know they belong.",
  "Let a child in your life know you're thinking of them, unprompted.",
  "Compliment the effort someone going through a hard season is putting in, not just what they achieved.",
  "Send someone new to your city a message telling them exactly why you're grateful for them.",
  "Give credit out loud today to someone whose work usually gets overlooked.",
  "Say something good about someone in your community to someone else today — the kind of thing that has a way of getting back to people.",
  "Send a small business owner nearby a message telling them exactly why you're grateful for them.",
  "Write down five things you actually like about yourself, and keep the list somewhere you'll see it again.",
  "Tell someone you live with (or a close friend, if you live alone) one specific thing you admire about them.",
  "Share something hopeful with a neighbor — they might need it today.",
  "Bring a mentor from your past something small — a coffee, a snack, a kind word.",
  "Take real notice of someone going through a hard season — ask how they're doing, and actually listen.",
  "Thank someone new for something you don't usually say thank you for.",
  "Tell a first responder exactly what makes them valuable to the people around them, not just what they do.",
  "If you're able, quietly cover a small cost for a caregiver today — a coffee, a fare, a few dollars — without making it a big deal.",
  "Write a neighbor a short note of encouragement and leave it where they'll find it.",
  "Compliment the effort someone in your community is putting in, not just what they achieved.",
  "Ask an elderly neighbor how they're really doing, and wait for the real answer.",
  "Ask a caregiver how they're really doing, and wait for the real answer.",
  "Tell someone quietly struggling exactly what makes them valuable to the people around them, not just what they do.",
  "Ask someone in your community how they're really doing, and wait for the real answer.",
  "Offer to carry, lift, fix, or fetch something for someone struggling with it today.",
  "Tell a nurse or doctor you know how they've shaped who you are.",
  "Recommend someone who helped you once for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Thank a first responder for something you don't usually say thank you for.",
  "Include someone in your community in something today — a meal, a plan, a conversation — so they know they belong.",
  "Tell someone you disagreed with recently one specific thing you admire about them.",
  "Let someone sitting alone know you're thinking of them, unprompted.",
  "Bring a coworker something small — a coffee, a snack, a kind word.",
  "Send someone who looks worn out a message telling them exactly why you're grateful for them.",
  "Do a small task for a parent you know without being asked.",
  "Celebrate a win a coworker had today — say it out loud.",
  "Text someone you haven't spoken to in a long time just to say you still think about them.",
  "Include a close friend in something today — a meal, a plan, a conversation — so they know they belong.",
  "Show up in person for something instead of sending a text — a visit, a call, a face-to-face conversation.",
  "Ask your partner (or the person closest to your heart) what would make today easier for them, then help make it happen.",
  "Tell a classmate one specific thing you admire about them.",
  "Give your partner (or the person closest to your heart) your full attention for five minutes today, phone away.",
  "If you're able, quietly cover a small cost for an old friend you've lost touch with today — a coffee, a fare, a few dollars — without making it a big deal.",
  "Check in on a delivery driver just to see how they're really doing.",
  "Really listen to your parent (or an elder in your life, or someone close to you) today, without planning what you'll say next.",
  "Offer to babysit, pet-sit, house-sit, or cover a responsibility for someone so they can have a break.",
  "Ask a nurse or doctor you know how they're really doing, and wait for the real answer.",
  "Celebrate a win someone going through a hard season had today — say it out loud.",
  "If you're able, quietly cover a small cost for a first responder today — a coffee, a fare, a few dollars — without making it a big deal.",
  "Forgive yourself today for something you've been quietly carrying, even if no one else needs to know.",
  "Say something good about a child in your life to someone else today — the kind of thing that has a way of getting back to people.",
  "Do a small task for someone going through a hard season without being asked.",
  "Write a mentor from your past a short note of encouragement and leave it where they'll find it.",
  "Bring something to share with everyone in a space you're part of today — home, work, class, or your street.",
  "Bring a family member something small — a coffee, a snack, a kind word.",
  "Give someone new a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Ask a mentor from your past how they're really doing, and wait for the real answer.",
  "Let someone go ahead of you today — in traffic, in line, in a conversation — and mean it.",
  "Compliment the effort someone teaching themselves something hard right now is putting in, not just what they achieved.",
  "Celebrate a win someone in your community had today — say it out loud.",
  "If you're able, quietly send an online friend a small gift card or a few dollars today — no big deal, just because.",
  "Thank your sibling (or someone who feels like one) for something you don't usually say thank you for.",
  "Take real notice of someone who looks worn out today — ask how they're doing, and actually listen.",
  "Send someone quietly struggling a message telling them exactly why you're grateful for them.",
  "Celebrate a win someone sitting alone had today — say it out loud.",
  "Say something good about an elderly neighbor to someone else today — the kind of thing that has a way of getting back to people.",
  "Do a small task for someone you disagreed with recently without being asked.",
  "Really listen to a close friend today, without planning what you'll say next.",
  "Bring a stranger something small — a coffee, a snack, a kind word.",
  "Make time today just for a coworker having a rough week, with nothing else competing for your attention.",
  "Include someone new to your city in something today — a meal, a plan, a conversation — so they know they belong.",
  "Greet a stranger today, strike up a simple conversation, and give them a genuine compliment.",
  "Let someone going through a hard season know you're thinking of them, unprompted.",
  "If you're able, quietly cover a small cost for a mentor from your past today — a coffee, a fare, a few dollars — without making it a big deal.",
  "Give a stranger a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Give a coworker a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Do a small task for a nurse or doctor you know without being asked.",
  "Compliment the effort a small business owner nearby is putting in, not just what they achieved.",
  "Give yourself the same grace today that you'd give a close friend going through what you're going through.",
  "Include someone you disagreed with recently in something today — a meal, a plan, a conversation — so they know they belong.",
  "Let someone in your community know you're thinking of them, unprompted.",
  "Make time today just for someone new to your city, with nothing else competing for your attention.",
  "Bring someone who looks worn out something small — a coffee, a snack, a kind word.",
  "Tell a service worker one specific thing you admire about them.",
  "Do a small task for a first responder without being asked.",
  "Share something hopeful with a stranger — they might need it today.",
  "Tell a service worker exactly what makes them valuable to the people around them, not just what they do.",
  "Share something hopeful with someone you live with (or a close friend, if you live alone) — they might need it today.",
  "Make time today just for someone you disagreed with recently, with nothing else competing for your attention.",
  "Check in on a first responder just to see how they're really doing.",
  "Celebrate a win your parent (or an elder in your life, or someone close to you) had today — say it out loud.",
  "Give an online friend a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Compliment the effort a coworker is putting in, not just what they achieved.",
  "Rest today without guilt — no productivity required to have earned it.",
  "Check in on someone quietly struggling just to see how they're really doing.",
  "Say something good about an old friend you've lost touch with to someone else today — the kind of thing that has a way of getting back to people.",
  "Include an elderly neighbor in something today — a meal, a plan, a conversation — so they know they belong.",
  "The next time you pass a stranger today, offer a genuine smile and ask how their day is going — then actually listen to the answer.",
  "Write a volunteer a short note of encouragement and leave it where they'll find it.",
  "Let a family member know you're thinking of them, unprompted.",
  "Ask someone how their family is doing, by name, and actually listen to the answer.",
  "Take a moment to really see your local barista or cashier today — ask how their day is going, and mean it.",
  "Give someone going through a hard season your full attention for five minutes today, phone away.",
  "Give someone who helped you once your full attention for five minutes today, phone away.",
  "Bring your sibling (or someone who feels like one) something small — a coffee, a snack, a kind word.",
  "Send a delivery driver a message telling them exactly why you're grateful for them.",
  "Recommend a parent you know for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Ask someone to teach you something they know and you don't — and really let them teach you.",
  "Check in on your sibling (or someone who feels like one) just to see how they're really doing.",
  "Recommend a new coworker or classmate for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Make time today just for someone who looks worn out, with nothing else competing for your attention.",
  "Check in on someone new to your city just to see how they're really doing.",
  "Make time today just for someone you live with (or a close friend, if you live alone), with nothing else competing for your attention.",
  "Celebrate a win someone you live with (or a close friend, if you live alone) had today — say it out loud.",
  "Let a delivery driver know you're thinking of them, unprompted.",
  "Tell your local barista or cashier exactly what makes them valuable to the people around them, not just what they do.",
  "Bring a classmate something small — a coffee, a snack, a kind word.",
  "Include someone going through a hard season in something today — a meal, a plan, a conversation — so they know they belong.",
  "Write a delivery driver a short note of encouragement and leave it where they'll find it.",
  "Leave a kind, honest review or shout-out for a local business, service, or person who did right by you.",
  "Recommend an online friend for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Say something good about a parent you know to someone else today — the kind of thing that has a way of getting back to people.",
  "Tell someone teaching themselves something hard right now one specific thing you admire about them.",
  "Recommend a close friend for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Give someone who looks worn out your full attention for five minutes today, phone away.",
  "Give a parent you know your full attention for five minutes today, phone away.",
  "Leave an encouraging comment on something someone made or posted, publicly, where others will see it too.",
  "Tell your pastor or a spiritual leader one specific thing you admire about them.",
  "Write a thank-you note to someone whose name you don't actually know — a delivery person, a cleaner, a security guard — and find a way to get it to them.",
  "Plan a small surprise — a note, a treat, a favor — for someone who always plans things for everyone else.",
  "Write a genuine, specific recommendation or reference for someone who could use one.",
  "Celebrate a win someone teaching themselves something hard right now had today — say it out loud.",
  "Include your partner (or the person closest to your heart) in something today — a meal, a plan, a conversation — so they know they belong.",
  "Really listen to your sibling (or someone who feels like one) today, without planning what you'll say next.",
  "Really listen to someone you live with (or a close friend, if you live alone) today, without planning what you'll say next.",
  "Thank a coworker having a rough week for something you don't usually say thank you for.",
  "Bring a new coworker or classmate something small — a coffee, a snack, a kind word.",
  "Offer a ride, a lift, or help getting somewhere to someone who needs it today.",
  "Make time today just for a close friend, with nothing else competing for your attention.",
  "Make time today just for a parent you know, with nothing else competing for your attention.",
  "Tell your partner (or the person closest to your heart) exactly what makes them valuable to the people around them, not just what they do.",
  "Check in on an old friend you've lost touch with just to see how they're really doing.",
  "Give your parent (or an elder in your life, or someone close to you) your full attention for five minutes today, phone away.",
  "Include a small business owner nearby in something today — a meal, a plan, a conversation — so they know they belong.",
  "Write yourself a short note of encouragement, the way you'd write one for someone else — and actually read it back.",
  "Bring someone you disagreed with recently something small — a coffee, a snack, a kind word.",
  "Cover a small cost for someone today, if you're able, without telling them it was you.",
  "Compliment the effort someone quietly struggling is putting in, not just what they achieved.",
  "Put your phone away completely during your next conversation today, whoever it's with.",
  "Tell someone whose work usually goes unnoticed one specific thing you admire about them.",
  "Bring a delivery driver something small — a coffee, a snack, a kind word.",
  "Speak a word of hope over yourself today, the same way you would over someone you love.",
  "Cook or prepare a meal for someone who's had a hard week, even if it's simple.",
  "Tell someone whose work usually goes unnoticed exactly what makes them valuable to the people around them, not just what they do.",
  "Send someone who helped you once a message telling them exactly why you're grateful for them.",
  "Give your local barista or cashier your full attention for five minutes today, phone away.",
  "Offer your specific skill or knowledge to someone for free today, even for twenty minutes.",
  "Write a coworker having a rough week a short note of encouragement and leave it where they'll find it.",
  "Tidy or pick up litter in a shared space today without being asked or thanked for it.",
  "Bring someone going through a hard season something small — a coffee, a snack, a kind word.",
  "Tell your partner (or the person closest to your heart) how they've shaped who you are.",
  "Compliment the effort someone who looks worn out is putting in, not just what they achieved.",
  "Give a close friend your full attention for five minutes today, phone away.",
  "Recommend a volunteer for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Say something good about someone new to someone else today — the kind of thing that has a way of getting back to people.",
  "Give a mentor from your past your full attention for five minutes today, phone away.",
  "Tell your parent (or an elder in your life, or someone close to you) exactly what makes them valuable to the people around them, not just what they do.",
  "Check in on your local barista or cashier just to see how they're really doing.",
  "Give someone teaching themselves something hard right now your full attention for five minutes today, phone away.",
  "Do a small task for someone teaching themselves something hard right now without being asked.",
  "Say something good about a mentor from your past to someone else today — the kind of thing that has a way of getting back to people.",
  "The next time an online friend shares a win with you, celebrate it loudly and specifically — a real reply, not just an emoji.",
  "Offer a stranger real, practical help today — carry something, hold a door, cover a small cost, whatever fits the moment.",
  "Thank your parent (or an elder in your life, or someone close to you) for something you don't usually say thank you for.",
  "Tell a nurse or doctor you know one specific thing you admire about them.",
  "Share something hopeful with a delivery driver — they might need it today.",
  "Thank a close friend for something you don't usually say thank you for.",
  "Write a coworker a short note of encouragement and leave it where they'll find it.",
  "Ask a nurse or doctor you know what would make today easier for them, then help make it happen.",
  "Really listen to your pastor or a spiritual leader today, without planning what you'll say next.",
  "Recommend a neighbor for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Tell someone quietly struggling one specific thing you admire about them.",
  "Sit with someone who's alone today — your presence is the help.",
  "Bring someone quietly struggling something small — a coffee, a snack, a kind word.",
  "Check in on someone teaching themselves something hard right now just to see how they're really doing.",
  "Thank someone quietly struggling for something you don't usually say thank you for.",
  "Ask a delivery driver how they're really doing, and wait for the real answer.",
  "Share a meal or a coffee with someone who might otherwise eat alone today.",
  "Give your pastor or a spiritual leader a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Thank a parent you know for something you don't usually say thank you for.",
  "Tell a delivery driver how they've shaped who you are.",
  "Really listen to your partner (or the person closest to your heart) today, without planning what you'll say next.",
  "Tell someone sitting alone how they've shaped who you are.",
  "Give your local barista or cashier a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Reach out to someone you admire from a distance and tell them so directly.",
  "Do a small task for your pastor or a spiritual leader without being asked.",
  "Share something hopeful with a close friend — they might need it today.",
  "Give someone sitting alone a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Thank a mentor from your past for something you don't usually say thank you for.",
  "Make time today just for your parent (or an elder in your life, or someone close to you), with nothing else competing for your attention.",
  "Compliment the effort a neighbor is putting in, not just what they achieved.",
  "Send someone whose work usually goes unnoticed a message telling them exactly why you're grateful for them.",
  "Check in on someone in your community just to see how they're really doing.",
  "Set a boundary today that protects your own peace, and don't apologize for it.",
  "Include an old friend you've lost touch with in something today — a meal, a plan, a conversation — so they know they belong.",
  "Really listen to a first responder today, without planning what you'll say next.",
  "Share something hopeful with your partner (or the person closest to your heart) — they might need it today.",
  "Compliment the effort an elderly neighbor is putting in, not just what they achieved.",
  "Thank a stranger like you mean it the next time one does something small and easy to overlook for you today.",
  "Say something good about someone you disagreed with recently to someone else today — the kind of thing that has a way of getting back to people.",
  "Write a teacher a short note of encouragement and leave it where they'll find it.",
  "Ask someone new what would make today easier for them, then help make it happen.",
  "Make time today just for a coworker, with nothing else competing for your attention.",
  "Notice a stranger working hard at something today — carrying groceries, finishing a tough task, pushing through a long shift — and tell them well done.",
  "Before your next kindness to someone else today, offer that same kindness to yourself first.",
  "Say something good about a classmate to someone else today — the kind of thing that has a way of getting back to people.",
  "Share something hopeful with an online friend — they might need it today.",
  "Give someone new to your city your full attention for five minutes today, phone away.",
  "Tell someone who helped you once exactly what makes them valuable to the people around them, not just what they do.",
  "Tell your local barista or cashier one specific thing you admire about them.",
  "Write your local barista or cashier a short note of encouragement and leave it where they'll find it.",
  "Tell your pastor or a spiritual leader how they've shaped who you are.",
  "Ask your pastor or a spiritual leader how they're really doing, and wait for the real answer.",
  "Send someone you live with (or a close friend, if you live alone) a message telling them exactly why you're grateful for them.",
  "Tell a service worker how they've shaped who you are.",
  "Bring someone whose work usually goes unnoticed something small — a coffee, a snack, a kind word.",
  "Tell someone sitting alone one specific thing you admire about them.",
  "Give a coworker having a rough week a small gift today — nothing expensive, and it can be something you make or already have, just something that shows you noticed them.",
  "Offer to help someone with a practical task today — groceries, a ride, a meal — since sometimes encouragement comes with hands and feet, not just words.",
  "Write a handwritten note to a coworker, neighbor, or family member telling them something specific you appreciate about them.",
  "Share a story with someone about how God turned a hard season in your life into something good — let it give them hope for their own situation.",
  "Reach out to someone going through a difficult time today. Don't try to fix it — just be present and listen.",
  "Tell someone about a time you watched them handle something hard with grace and strength. Help them see their own resilience.",
  "Encourage someone facing a big decision or change. Tell them plainly that you believe in them.",
  "Pay for the coffee or meal of the person behind you in line, with a note that says \"You matter and you're loved.\"",
  "Offer to take something off someone's plate today — run an errand, or just sit with them in their tiredness.",
  "Offer a kind word to a stranger today — it could be the highlight of their whole day.",
  "Send an encouraging text to someone anxious about their future, reminding them they're not walking it alone.",
  "Share something funny or lighthearted with someone who's been heavy-hearted lately. Laughter can be a real gift.",
  "Point out a gift or blessing in the life of someone who's struggling to see any good right now.",
  "Remind someone stuck in shame or regret that they deserve a fresh start — help them see today as a new beginning.",
  "Share a story of God's faithfulness in your own life with someone who's struggling to trust that good things can happen for them.",
  "Encourage someone whose life has taken an unexpected turn — help them see that a redirection can lead somewhere beautiful.",
  "Pray for someone by name today, asking God to fill them with hope — then let them know you prayed for them.",
  "Notice something specific someone does well and tell them. Help them see their own gifts.",
  "Let someone know today, plainly, that they are not alone.",
  "Apologize to someone if you need to, or forgive someone who's hurt you — release the weight of holding onto it.",
  "Acknowledge someone's courage in facing something hard today. They may not see their own bravery the way you do.",
  "Help meet a practical need for someone today — a meal, a ride, help with a task, or simply your time.",
  "Tell someone about a real, positive impact they've had on your life or someone else's. Help them see their purpose.",
  "Encourage someone struggling with uncertainty today. Remind them they don't have to have it all figured out.",
  "Send an encouraging word to someone who is usually the one encouraging everybody else. Encouragers need encouragement too.",
  "Tell someone specifically what you love about them and how they bring you joy.",
  "Celebrate someone's growth today, even if they're not yet where they want to be. Growth is a journey, not a destination.",
  "Respond to someone who's been testing your patience today with unexpected kindness instead.",
  "Share an uplifting song, book, or quote with someone who needs their heart filled with something beautiful today.",
  "Share a story of how God used one of your own weaknesses or struggles to help someone else — show them their pain can have purpose too.",
  "Encourage someone who feels like their prayers aren't being heard. Remind them that God sees a seeking heart.",
  "Offer to pray with someone who's anxious about something today — praying together can break the grip of worry.",
  "Encourage someone fighting a battle they can't win alone. Remind them they're not fighting it alone either.",
  "Be a calm, steady presence today for someone who's overwhelmed.",
  "Help someone see something good developing in their current, difficult season — growth, strength, character.",
  "Encourage someone who feels far from God today. Remind them He's closer than they think, and their honest prayers are welcome just as they are.",
  "Remind someone who feels unlovable, specifically, why they matter to you.",
  "Share a specific way you've experienced God's goodness recently — your story might help someone else trust Him too.",
  "Show love today to someone who might be feeling lonely — a kind word, a small gift, or just your time.",
  "Compliment someone today on how they've been a light in your life or someone else's. Help them see their own brightness.",
  "Encourage someone who's in a season of waiting. Remind them the waiting isn't wasted — it's preparing them.",
  "Bring refreshment to someone who seems spiritually or emotionally dry today — an encouraging word, a listening ear, a small kindness.",
  "Help someone see how God might be working good out of a hard situation they're in. Offer your perspective gently.",
  "Sit with someone who is grieving or struggling without rushing them toward feeling better. Just remind them morning comes.",
  "Encourage someone whose plans just fell through. Help them consider that God might be redirecting them toward something better.",
  "Remind someone who feels shaken or unstable today of the deep roots they have in God's love and faithfulness.",
  "Speak truth today over someone who's been believing something false about themselves. Help them see themselves the way God does.",
  "Reach out to someone who's heartbroken and let them know, clearly, that they're not alone.",
  "Thank someone today who's been quietly, consistently kind. Let them know it hasn't gone unnoticed.",
];
