// 366 quotes on the power of encouragement and hope -- one for every day of
// the year, including a leap day, with no repeats. Picked via pickForDay,
// same as every other full-366 content bank.
//
// This file used to also hold ~275 short fictional "vignette" entries
// (type: "story") mixed in alongside a much smaller set of quotes -- see
// git history if you need them for reference. They were dead weight (never
// actually shown to a user; the only consumer of this file always filtered
// to type === "quote") and were removed, then the quote set itself was
// expanded from 91 to a full 366 so it never has to repeat within a year,
// same guarantee as every other daily content bank.

const WISDOM = [
  {"type":"quote","text":"Wherever there is a human being, there is an opportunity for a kindness.","source":"Seneca"},
  {"type":"quote","text":"A hedge between keeps friendship green.","source":"Proverb"},
  {"type":"quote","text":"The soul would have no rainbow had the eyes no tears.","source":"John Vance Cheney"},
  {"type":"quote","text":"A single act of kindness throws out roots in all directions, and the roots spring up and make new trees.","source":"Amelia Earhart"},
  {"type":"quote","text":"Every saint has a past, and every sinner has a future.","source":"Oscar Wilde"},
  {"type":"quote","text":"Hope begins in the dark, the stubborn hope that if you just show up and try to do the right thing, the dawn will come.","source":"Anne Lamott"},
  {"type":"quote","text":"The soul is healed by being with children.","source":"Fyodor Dostoevsky"},
  {"type":"quote","text":"How wonderful it is that nobody need wait a single moment before starting to improve the world.","source":"Anne Frank"},
  {"type":"quote","text":"Start each day with a grateful heart.","source":"Unknown"},
  {"type":"quote","text":"Faith is taking the first step even when you don't see the whole staircase.","source":"Martin Luther King Jr."},
  {"type":"quote","text":"The best portion of a good person's life: their little, nameless, unremembered acts of kindness and love.","source":"William Wordsworth"},
  {"type":"quote","text":"Just when the caterpillar thought the world was over, it became a butterfly.","source":"Unknown"},
  {"type":"quote","text":"Hardships often prepare ordinary people for an extraordinary destiny.","source":"C.S. Lewis"},
  {"type":"quote","text":"Worry does not empty tomorrow of its sorrow, it empties today of its strength.","source":"Corrie ten Boom"},
  {"type":"quote","text":"Kindness gives birth to kindness.","source":"Sophocles"},
  {"type":"quote","text":"A good head and a good heart are always a formidable combination.","source":"Nelson Mandela"},
  {"type":"quote","text":"Never be afraid to trust an unknown future to a known God.","source":"Corrie ten Boom"},
  {"type":"quote","text":"For every dark night, there's a brighter day.","source":"Tupac Shakur"},
  {"type":"quote","text":"It is not how much we give, but how much love we put into giving.","source":"Mother Teresa"},
  {"type":"quote","text":"Everything that irritates us about others can lead us to an understanding of ourselves.","source":"Carl Jung"},
  {"type":"quote","text":"The smallest act of kindness is worth more than the grandest intention.","source":"Oscar Wilde"},
  {"type":"quote","text":"In the middle of every difficulty lies opportunity.","source":"Albert Einstein"},
  {"type":"quote","text":"God whispers to us in our pleasures... but shouts in our pains: it is his megaphone to rouse a deaf world.","source":"C.S. Lewis"},
  {"type":"quote","text":"You never know how much your encouragement will mean to someone until you give it.","source":"Unknown"},
  {"type":"quote","text":"I have found that among its other benefits, giving liberates the soul of the giver.","source":"Maya Angelou"},
  {"type":"quote","text":"Life is not measured by the number of breaths we take, but by the moments that take our breath away.","source":"Attr. Maya Angelou"},
  {"type":"quote","text":"Even the smallest act of caring for another person is like a drop of water — it will make ripples through the entire pond.","source":"Unknown"},
  {"type":"quote","text":"A little bit of encouragement goes further than a whole lot of criticism.","source":"Unknown"},
  {"type":"quote","text":"Carry out a random act of kindness, with no expectation of reward.","source":"Princess Diana"},
  {"type":"quote","text":"Do all the good you can, by all the means you can, in all the ways you can, to all the people you can, for as long as you can.","source":"Attr. John Wesley"},
  {"type":"quote","text":"The best way to cheer yourself up is to try to cheer somebody else up.","source":"Mark Twain"},
  {"type":"quote","text":"Try to be a rainbow in someone's cloud.","source":"Maya Angelou"},
  {"type":"quote","text":"Never lose an opportunity of seeing anything that is beautiful.","source":"Ralph Waldo Emerson"},
  {"type":"quote","text":"Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.'","source":"C.S. Lewis"},
  {"type":"quote","text":"Joy is the simplest form of gratitude.","source":"Karl Barth"},
  {"type":"quote","text":"As we let our own light shine, we unconsciously give other people permission to do the same.","source":"Marianne Williamson"},
  {"type":"quote","text":"Small deeds done are better than great deeds planned.","source":"Peter Marshall"},
  {"type":"quote","text":"Alone we can do so little; together we can do so much.","source":"Helen Keller"},
  {"type":"quote","text":"Where there is great love, there are always miracles.","source":"Willa Cather"},
  {"type":"quote","text":"Although the world is full of suffering, it is also full of the overcoming of it.","source":"Helen Keller"},
  {"type":"quote","text":"Every day may not be good, but there is something good in every day.","source":"Unknown"},
  {"type":"quote","text":"The greatest thing in the world is to know how to belong to oneself, and still care for others.","source":"Attr. Michel de Montaigne"},
  {"type":"quote","text":"Sometimes the smallest step in the right direction ends up being the biggest step of your life.","source":"Unknown"},
  {"type":"quote","text":"People will forget what you said, people will forget what you did, but people will never forget how you made them feel.","source":"Maya Angelou"},
  {"type":"quote","text":"We must accept finite disappointment, but never lose infinite hope.","source":"Martin Luther King Jr."},
  {"type":"quote","text":"Once you choose hope, anything's possible.","source":"Christopher Reeve"},
  {"type":"quote","text":"A single sunbeam is enough to drive away many shadows.","source":"Francis of Assisi"},
  {"type":"quote","text":"Gratitude turns what we have into enough.","source":"Unknown"},
  {"type":"quote","text":"The greatest glory in living lies not in never falling, but in rising every time we fall.","source":"Nelson Mandela"},
  {"type":"quote","text":"Not all of us can do great things, but we can do small things with great love.","source":"Mother Teresa"},
  {"type":"quote","text":"Even the darkest night will end and the sun will rise.","source":"Victor Hugo"},
  {"type":"quote","text":"It is only with the heart that one can see rightly; what is essential is invisible to the eye.","source":"Antoine de Saint-Exupéry"},
  {"type":"quote","text":"One kind word can warm three winter months.","source":"Japanese proverb"},
  {"type":"quote","text":"The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.","source":"Charles Dickens"},
  {"type":"quote","text":"In spite of everything, I still believe that people are really good at heart.","source":"Anne Frank"},
  {"type":"quote","text":"Kindness is the language which the deaf can hear and the blind can see.","source":"Mark Twain"},
  {"type":"quote","text":"Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.","source":"Helen Keller"},
  {"type":"quote","text":"What lies behind us and what lies before us are tiny matters compared to what lies within us.","source":"Attr. Ralph Waldo Emerson"},
  {"type":"quote","text":"Peace begins with a smile.","source":"Mother Teresa"},
  {"type":"quote","text":"Life's most persistent and urgent question is: what are you doing for others?","source":"Martin Luther King Jr."},
  {"type":"quote","text":"No one has ever become poor by giving.","source":"Anne Frank"},
  {"type":"quote","text":"Kind words can be short and easy to speak, but their echoes are truly endless.","source":"Mother Teresa"},
  {"type":"quote","text":"No act of kindness, no matter how small, is ever wasted.","source":"Aesop"},
  {"type":"quote","text":"The greatest gift you can give someone is your presence.","source":"Thich Nhat Hanh"},
  {"type":"quote","text":"Look for the helpers. You will always find people who are helping.","source":"Fred Rogers"},
  {"type":"quote","text":"A warm smile is the universal language of kindness.","source":"Unknown"},
  {"type":"quote","text":"Be the reason someone believes in the goodness of people.","source":"Unknown"},
  {"type":"quote","text":"When it is darkest, we can see the stars.","source":"Ralph Waldo Emerson"},
  {"type":"quote","text":"You give but little when you give of your possessions. It is when you give of yourself that you truly give.","source":"Kahlil Gibran"},
  {"type":"quote","text":"When you have nothing left but God, you become aware that God is enough.","source":"Attr. Corrie ten Boom"},
  {"type":"quote","text":"Hope is being able to see that there is light despite all of the darkness.","source":"Desmond Tutu"},
  {"type":"quote","text":"Be kind, for everyone you meet is fighting a hard battle.","source":"Attr. Ian Maclaren"},
  {"type":"quote","text":"Encouragement is oxygen to the soul.","source":"Unknown"},
  {"type":"quote","text":"Three things in human life are important: the first is to be kind; the second is to be kind; and the third is to be kind.","source":"Henry James"},
  {"type":"quote","text":"It's not what you look at that matters, it's what you see.","source":"Henry David Thoreau"},
  {"type":"quote","text":"Every act of love and kindness leaves this world a little better than it found it.","source":"Unknown"},
  {"type":"quote","text":"Encouragement costs nothing to give, but it is worth everything to receive.","source":"Unknown"},
  {"type":"quote","text":"A candle loses nothing by lighting another candle.","source":"Attr. James Keller"},
  {"type":"quote","text":"We rise by lifting others.","source":"Robert Ingersoll"},
  {"type":"quote","text":"There is no exercise better for the heart than reaching down and lifting people up.","source":"Attr. John Andrew Holmes"},
  {"type":"quote","text":"Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.","source":"Martin Luther King Jr."},
  {"type":"quote","text":"What we do for ourselves dies with us. What we do for others and the world remains and is immortal.","source":"Albert Pike"},
  {"type":"quote","text":"Tough times never last, but tough people do.","source":"Robert H. Schuller"},
  {"type":"quote","text":"Hope is the thing with feathers that perches in the soul.","source":"Emily Dickinson"},
  {"type":"quote","text":"The world is full of nice people. If you can't find one, be one.","source":"Unknown"},
  {"type":"quote","text":"This too shall pass.","source":"Persian proverb"},
  {"type":"quote","text":"Where there is love and encouragement, there is always hope for a new day.","source":"Unknown"},
  {"type":"quote","text":"It always seems impossible until it's done.","source":"Nelson Mandela"},
  {"type":"quote","text":"A joyful heart is good medicine.","source":"Proverbs 17:22, paraphrase"},
  {"type":"quote","text":"The greatest use of a life is to spend it on something that will outlast it.","source":"William James"},
  {"type":"quote","text":"A word of encouragement during a failure is worth more than an hour of praise after success.","source":"Unknown"},
  {"type":"quote","text":"In a gentle way, you can shake the world.","source":"Mahatma Gandhi"},
  {"type":"quote","text":"We make a living by what we get, but we make a life by what we give.","source":"Winston Churchill"},
  {"type":"quote","text":"No one is useless in this world who lightens the burdens of another.","source":"Charles Dickens"},
  {"type":"quote","text":"Kind words do not cost much. Yet they accomplish much.","source":"Blaise Pascal"},
  {"type":"quote","text":"The simplest acts of kindness are by far more powerful than a thousand heads bowing in prayer.","source":"Mahatma Gandhi"},
  {"type":"quote","text":"Be kind whenever possible. It is always possible.","source":"Dalai Lama"},
  {"type":"quote","text":"There is no such thing as a small act of kindness. Every act creates a ripple with no logical end.","source":"Scott Adams"},
  {"type":"quote","text":"Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.","source":"Lao Tzu"},
  {"type":"quote","text":"How far that little candle throws his beams! So shines a good deed in a weary world.","source":"William Shakespeare"},
  {"type":"quote","text":"If you want others to be happy, practice compassion. If you want to be happy, practice compassion.","source":"Dalai Lama"},
  {"type":"quote","text":"We can't help everyone, but everyone can help someone.","source":"Ronald Reagan"},
  {"type":"quote","text":"The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.","source":"Attr. Ralph Waldo Emerson"},
  {"type":"quote","text":"Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.","source":"Desmond Tutu"},
  {"type":"quote","text":"Never doubt that a small group of thoughtful, committed citizens can change the world.","source":"Margaret Mead"},
  {"type":"quote","text":"To the world you may be one person, but to one person you may be the world.","source":"Unknown"},
  {"type":"quote","text":"Compassion is the basis of all morality.","source":"Arthur Schopenhauer"},
  {"type":"quote","text":"Courage is not the absence of fear, but the triumph over it.","source":"Nelson Mandela"},
  {"type":"quote","text":"When you reach the end of your rope, tie a knot in it and hang on.","source":"Attr. Franklin D. Roosevelt"},
  {"type":"quote","text":"Fall seven times, stand up eight.","source":"Japanese proverb"},
  {"type":"quote","text":"The wound is the place where the Light enters you.","source":"Rumi"},
  {"type":"quote","text":"Out of difficulties grow miracles.","source":"Jean de La Bruyère"},
  {"type":"quote","text":"You may say I'm a dreamer, but I'm not the only one.","source":"John Lennon"},
  {"type":"quote","text":"A person who never made a mistake never tried anything new.","source":"Attr. Albert Einstein"},
  {"type":"quote","text":"Turn your wounds into wisdom.","source":"Oprah Winfrey"},
  {"type":"quote","text":"The struggle you're in today is developing the strength you need for tomorrow.","source":"Robert Tew"},
  {"type":"quote","text":"Storms make trees take deeper roots.","source":"Dolly Parton"},
  {"type":"quote","text":"You are never too old to set another goal or to dream a new dream.","source":"C.S. Lewis"},
  {"type":"quote","text":"Perhaps all the dragons in our lives are princesses who are only waiting to see us act, just once, with beauty and courage.","source":"Rainer Maria Rilke"},
  {"type":"quote","text":"Nothing is impossible, the word itself says 'I'm possible'!","source":"Audrey Hepburn"},
  {"type":"quote","text":"Believe you can and you're halfway there.","source":"Theodore Roosevelt"},
  {"type":"quote","text":"Keep your face always toward the sunshine, and shadows will fall behind you.","source":"Walt Whitman"},
  {"type":"quote","text":"The only way out is through.","source":"Robert Frost"},
  {"type":"quote","text":"Everything you've ever wanted is on the other side of fear.","source":"Attr. George Addair"},
  {"type":"quote","text":"You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.","source":"Eleanor Roosevelt"},
  {"type":"quote","text":"Do not judge me by my success, judge me by how many times I fell down and got back up again.","source":"Nelson Mandela"},
  {"type":"quote","text":"Hope smiles from the threshold of the year to come, whispering, 'it will be happier.'","source":"Alfred Lord Tennyson"},
  {"type":"quote","text":"Hope is a waking dream.","source":"Aristotle"},
  {"type":"quote","text":"Hope is patience with the lamp lit.","source":"Attr. Tertullian"},
  {"type":"quote","text":"While there's life, there's hope.","source":"Marcus Tullius Cicero"},
  {"type":"quote","text":"Hope never abandons you; you abandon it.","source":"George Weinberg"},
  {"type":"quote","text":"Hope is the only thing stronger than fear.","source":"Suzanne Collins"},
  {"type":"quote","text":"The very least you can do in your life is figure out what you hope for. And the most you can do is live inside that hope.","source":"Barbara Kingsolver"},
  {"type":"quote","text":"To live without hope is to cease to live.","source":"Fyodor Dostoevsky"},
  {"type":"quote","text":"Gratitude is not only the greatest of virtues, but the parent of all others.","source":"Marcus Tullius Cicero"},
  {"type":"quote","text":"Enjoy the little things, for one day you may look back and realize they were the big things.","source":"Robert Brault"},
  {"type":"quote","text":"Piglet noticed that even though he had a Very Small Heart, it could hold a rather large amount of Gratitude.","source":"A.A. Milne"},
  {"type":"quote","text":"Gratitude is when memory is stored in the heart and not in the mind.","source":"Lionel Hampton"},
  {"type":"quote","text":"When I started counting my blessings, my whole life turned around.","source":"Willie Nelson"},
  {"type":"quote","text":"Silent gratitude isn't very much use to anyone.","source":"Gertrude Stein"},
  {"type":"quote","text":"Gratitude can transform common days into thanksgivings.","source":"William Arthur Ward"},
  {"type":"quote","text":"Feeling gratitude and not expressing it is like wrapping a present and not giving it.","source":"William Arthur Ward"},
  {"type":"quote","text":"Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom.","source":"Marcel Proust"},
  {"type":"quote","text":"The unthankful heart discovers no mercies; but the thankful heart will find, in every hour, some heavenly blessings.","source":"Henry Ward Beecher"},
  {"type":"quote","text":"Friendship is one mind in two bodies.","source":"Aristotle"},
  {"type":"quote","text":"A friend is someone who knows all about you and still loves you.","source":"Elbert Hubbard"},
  {"type":"quote","text":"It is one of the blessings of old friends that you can afford to be stupid with them.","source":"Ralph Waldo Emerson"},
  {"type":"quote","text":"Rare as is true love, true friendship is rarer.","source":"Jean de La Fontaine"},
  {"type":"quote","text":"True friendship multiplies the good in life and divides its evils.","source":"Baltasar Gracián"},
  {"type":"quote","text":"A true friend is someone who sees the pain in your eyes while everyone else believes the smile on your face.","source":"Unknown"},
  {"type":"quote","text":"Friends are the family we choose for ourselves.","source":"Edna Buchanan"},
  {"type":"quote","text":"The language of friendship is not words but meanings.","source":"Henry David Thoreau"},
  {"type":"quote","text":"Real generosity toward the future lies in giving all to the present.","source":"Albert Camus"},
  {"type":"quote","text":"Remember that the happiest people are not those getting more, but those giving more.","source":"H. Jackson Brown Jr."},
  {"type":"quote","text":"Forgiveness is the fragrance the violet sheds on the heel that has crushed it.","source":"Mark Twain"},
  {"type":"quote","text":"The weak can never forgive. Forgiveness is the attribute of the strong.","source":"Mahatma Gandhi"},
  {"type":"quote","text":"To forgive is to set a prisoner free and discover that the prisoner was you.","source":"Lewis B. Smedes"},
  {"type":"quote","text":"Forgiveness does not change the past, but it does enlarge the future.","source":"Paul Boese"},
  {"type":"quote","text":"Holding on to anger is like drinking poison and expecting the other person to die.","source":"Attr. Buddha"},
  {"type":"quote","text":"He who cannot forgive others breaks the bridge over which he himself must pass.","source":"George Herbert"},
  {"type":"quote","text":"Always forgive your enemies; nothing annoys them so much.","source":"Oscar Wilde"},
  {"type":"quote","text":"Humility is not thinking less of yourself, it's thinking of yourself less.","source":"Attr. C.S. Lewis"},
  {"type":"quote","text":"The soil in which humility thrives is gratitude.","source":"Ann Voskamp"},
  {"type":"quote","text":"Pride makes us artificial and humility makes us real.","source":"Thomas Merton"},
  {"type":"quote","text":"It is not the load that breaks you down, it's the way you carry it.","source":"Lena Horne"},
  {"type":"quote","text":"When we are no longer able to change a situation, we are challenged to change ourselves.","source":"Viktor Frankl"},
  {"type":"quote","text":"That which does not kill us makes us stronger.","source":"Friedrich Nietzsche"},
  {"type":"quote","text":"Rock bottom became the solid foundation on which I rebuilt my life.","source":"J.K. Rowling"},
  {"type":"quote","text":"The bamboo that bends is stronger than the oak that resists.","source":"Japanese proverb"},
  {"type":"quote","text":"A smooth sea never made a skilled sailor.","source":"Attr. Franklin D. Roosevelt"},
  {"type":"quote","text":"The oak fought the wind and was broken, the willow bent when it must and survived.","source":"Robert Jordan"},
  {"type":"quote","text":"When the going gets tough, the tough get going.","source":"Joseph P. Kennedy"},
  {"type":"quote","text":"It does not matter how slowly you go as long as you do not stop.","source":"Confucius"},
  {"type":"quote","text":"Patience is bitter, but its fruit is sweet.","source":"Aristotle"},
  {"type":"quote","text":"Rivers know this: there is no hurry. We shall get there some day.","source":"A.A. Milne"},
  {"type":"quote","text":"Adopt the pace of nature: her secret is patience.","source":"Ralph Waldo Emerson"},
  {"type":"quote","text":"Trees that are slow to grow bear the best fruit.","source":"Molière"},
  {"type":"quote","text":"Everything comes to him who hustles while he waits.","source":"Thomas Edison"},
  {"type":"quote","text":"Patience is not simply the ability to wait — it's how we behave while we're waiting.","source":"Joyce Meyer"},
  {"type":"quote","text":"Joy is not in things; it is in us.","source":"Richard Wagner"},
  {"type":"quote","text":"Joy does not simply happen to us. We have to choose joy and keep choosing it every day.","source":"Henri Nouwen"},
  {"type":"quote","text":"Those who bring sunshine to the lives of others cannot keep it from themselves.","source":"J.M. Barrie"},
  {"type":"quote","text":"Find a place inside where there's joy, and the joy will burn out the pain.","source":"Joseph Campbell"},
  {"type":"quote","text":"Happiness is not something ready made. It comes from your own actions.","source":"Dalai Lama"},
  {"type":"quote","text":"A little spark of kindling joy sets a whole wood aflame.","source":"Dante Alighieri"},
  {"type":"quote","text":"Where there is love there is life.","source":"Mahatma Gandhi"},
  {"type":"quote","text":"Love cures people — both the ones who give it and the ones who receive it.","source":"Karl Menninger"},
  {"type":"quote","text":"We are not the same anymore after we care for someone. We are not the same after we hear their story.","source":"Unknown"},
  {"type":"quote","text":"To love and be loved is to feel the sun from both sides.","source":"David Viscott"},
  {"type":"quote","text":"At the touch of love everyone becomes a poet.","source":"Plato"},
  {"type":"quote","text":"Love recognizes no barriers.","source":"Maya Angelou"},
  {"type":"quote","text":"There is no remedy for love but to love more.","source":"Henry David Thoreau"},
  {"type":"quote","text":"You yourself, as much as anybody in the entire universe, deserve your love and affection.","source":"Attr. Buddha"},
  {"type":"quote","text":"Be yourself; everyone else is already taken.","source":"Oscar Wilde"},
  {"type":"quote","text":"You are not a drop in the ocean. You are the entire ocean in a drop.","source":"Rumi"},
  {"type":"quote","text":"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.","source":"Attr. Ralph Waldo Emerson"},
  {"type":"quote","text":"What you think of yourself is much more important than what others think of you.","source":"Seneca"},
  {"type":"quote","text":"Know, first, who you are, and then adorn yourself accordingly.","source":"Epictetus"},
  {"type":"quote","text":"Your value doesn't decrease based on someone's inability to see your worth.","source":"Unknown"},
  {"type":"quote","text":"I am not what happened to me, I am what I choose to become.","source":"Carl Jung"},
  {"type":"quote","text":"There is no greater agony than bearing an untold story inside you.","source":"Maya Angelou"},
  {"type":"quote","text":"Character is doing the right thing when nobody's looking.","source":"Attr. J.C. Watts"},
  {"type":"quote","text":"The true measure of a man is how he treats someone who can do him absolutely no good.","source":"Samuel Johnson"},
  {"type":"quote","text":"Nearly all men can stand adversity, but if you want to test a man's character, give him power.","source":"Abraham Lincoln"},
  {"type":"quote","text":"Character is much easier kept than recovered.","source":"Thomas Paine"},
  {"type":"quote","text":"Watch your thoughts, they become words. Watch your words, they become actions.","source":"Attr. Lao Tzu"},
  {"type":"quote","text":"Change your thoughts and you change your world.","source":"Norman Vincent Peale"},
  {"type":"quote","text":"Every new beginning comes from some other beginning's end.","source":"Seneca"},
  {"type":"quote","text":"It's never too late to be what you might have been.","source":"Attr. George Eliot"},
  {"type":"quote","text":"The secret of getting ahead is getting started.","source":"Mark Twain"},
  {"type":"quote","text":"Don't watch the clock; do what it does. Keep going.","source":"Sam Levenson"},
  {"type":"quote","text":"Start where you are. Use what you have. Do what you can.","source":"Arthur Ashe"},
  {"type":"quote","text":"The best time to plant a tree was 20 years ago. The second best time is now.","source":"Chinese proverb"},
  {"type":"quote","text":"You can't go back and change the beginning, but you can start where you are and change the ending.","source":"Attr. C.S. Lewis"},
  {"type":"quote","text":"A journey of a thousand miles begins with a single step.","source":"Lao Tzu"},
  {"type":"quote","text":"It is during our darkest moments that we must focus to see the light.","source":"Attr. Aristotle"},
  {"type":"quote","text":"Every flower must grow through dirt.","source":"Unknown"},
  {"type":"quote","text":"Stars can't shine without darkness.","source":"D.H. Sidebottom"},
  {"type":"quote","text":"There is a crack in everything, that's how the light gets in.","source":"Leonard Cohen"},
  {"type":"quote","text":"Even a small star shines in the darkness.","source":"Finnish proverb"},
  {"type":"quote","text":"Peace cannot be kept by force; it can only be achieved by understanding.","source":"Albert Einstein"},
  {"type":"quote","text":"Nothing can bring you peace but yourself.","source":"Ralph Waldo Emerson"},
  {"type":"quote","text":"Peace is not the absence of conflict, but the ability to cope with it.","source":"Attr. Ronald Reagan"},
  {"type":"quote","text":"If you want to make peace with your enemy, you have to work with your enemy. Then he becomes your partner.","source":"Nelson Mandela"},
  {"type":"quote","text":"Contentment is not the fulfillment of what you want, but the realization of how much you already have.","source":"Unknown"},
  {"type":"quote","text":"He who is not contented with what he has, would not be contented with what he would like to have.","source":"Socrates"},
  {"type":"quote","text":"It is not the man who has too little, but the man who craves more, that is poor.","source":"Seneca"},
  {"type":"quote","text":"Wanting to be someone else is a waste of the person you are.","source":"Marilyn Monroe"},
  {"type":"quote","text":"Happiness is not having what you want but wanting what you have.","source":"Attr. Rabbi Hyman Schachtel"},
  {"type":"quote","text":"Integrity is doing the right thing, even when no one is watching.","source":"Attr. C.S. Lewis"},
  {"type":"quote","text":"The time is always right to do what is right.","source":"Martin Luther King Jr."},
  {"type":"quote","text":"Whoever is careless with the truth in small matters cannot be trusted with important matters.","source":"Albert Einstein"},
  {"type":"quote","text":"Real integrity is doing the right thing, knowing that nobody's going to know whether you did it or not.","source":"Oprah Winfrey"},
  {"type":"quote","text":"Trust is built with consistency.","source":"Lincoln Chafee"},
  {"type":"quote","text":"An ounce of practice is worth more than tons of preaching.","source":"Mahatma Gandhi"},
  {"type":"quote","text":"Wisdom begins in wonder.","source":"Socrates"},
  {"type":"quote","text":"The only true wisdom is in knowing you know nothing.","source":"Socrates"},
  {"type":"quote","text":"Knowing yourself is the beginning of all wisdom.","source":"Aristotle"},
  {"type":"quote","text":"We do not learn from experience... we learn from reflecting on experience.","source":"John Dewey"},
  {"type":"quote","text":"Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.","source":"Rumi"},
  {"type":"quote","text":"A wise man learns more from a fool than a fool from a wise man.","source":"Baltasar Gracián"},
  {"type":"quote","text":"The only source of knowledge is experience.","source":"Attr. Albert Einstein"},
  {"type":"quote","text":"Volunteers do not necessarily have the time; they just have the heart.","source":"Elizabeth Andrew"},
  {"type":"quote","text":"The best way to find yourself is to lose yourself in the service of others.","source":"Mahatma Gandhi"},
  {"type":"quote","text":"Only a life lived for others is a life worthwhile.","source":"Albert Einstein"},
  {"type":"quote","text":"Service to others is the rent you pay for your room here on earth.","source":"Muhammad Ali"},
  {"type":"quote","text":"Listening is a magnetic and strange thing, a creative force.","source":"Brenda Ueland"},
  {"type":"quote","text":"Most of the successful people I've known are the ones who do more listening than talking.","source":"Bernard Baruch"},
  {"type":"quote","text":"To listen well is as powerful a means of communication and influence as to talk well.","source":"John Marshall"},
  {"type":"quote","text":"We have two ears and one mouth so that we can listen twice as much as we speak.","source":"Attr. Epictetus"},
  {"type":"quote","text":"The most basic and powerful way to connect to another person is to listen. Just listen.","source":"Rachel Naomi Remen"},
  {"type":"quote","text":"Sympathy is two hearts tugging at one load.","source":"Attr. Charles H. Parkhurst"},
  {"type":"quote","text":"Grief is the price we pay for love.","source":"Attr. Queen Elizabeth II"},
  {"type":"quote","text":"What we have once enjoyed we can never lose; all that we love deeply becomes a part of us.","source":"Attr. Helen Keller"},
  {"type":"quote","text":"The reality is that you will grieve forever. You will not 'get over' the loss of a loved one; you will learn to live with it.","source":"Elisabeth Kübler-Ross"},
  {"type":"quote","text":"Tears are words the heart can't express.","source":"Unknown"},
  {"type":"quote","text":"There is a sacredness in tears.","source":"Washington Irving"},
  {"type":"quote","text":"Grief never ends, but it changes. It's a passage, not a place to stay.","source":"Unknown"},
  {"type":"quote","text":"You never lose by loving. You always lose by holding back.","source":"Barbara De Angelis"},
  {"type":"quote","text":"A grandchild fills a space in your heart that you never knew was empty.","source":"Unknown"},
  {"type":"quote","text":"The love of a family is life's greatest blessing.","source":"Unknown"},
  {"type":"quote","text":"Family is not an important thing. It's everything.","source":"Attr. Michael J. Fox"},
  {"type":"quote","text":"Children are not things to be molded, but are people to be unfolded.","source":"Jess Lair"},
  {"type":"quote","text":"A child's life is like a piece of paper on which every person leaves a mark.","source":"Chinese proverb"},
  {"type":"quote","text":"There is no such thing as a perfect parent, so just be a real one.","source":"Sue Atkins"},
  {"type":"quote","text":"Where there is a mother in the house, matters speed well.","source":"Amos Bronson Alcott"},
  {"type":"quote","text":"Music can change the world because it can change people.","source":"Bono"},
  {"type":"quote","text":"Where words fail, music speaks.","source":"Hans Christian Andersen"},
  {"type":"quote","text":"Music gives a soul to the universe, wings to the mind, flight to the imagination.","source":"Attr. Plato"},
  {"type":"quote","text":"Art washes away from the soul the dust of everyday life.","source":"Pablo Picasso"},
  {"type":"quote","text":"Unity is strength. When there is teamwork and collaboration, wonderful things can be achieved.","source":"Mattie Stepanek"},
  {"type":"quote","text":"Coming together is a beginning; keeping together is progress; working together is success.","source":"Attr. Henry Ford"},
  {"type":"quote","text":"No one can whistle a symphony. It takes a whole orchestra to play it.","source":"H.E. Luccock"},
  {"type":"quote","text":"If everyone is moving forward together, then success takes care of itself.","source":"Attr. Henry Ford"},
  {"type":"quote","text":"For it is in giving that we receive.","source":"Attr. Francis of Assisi"},
  {"type":"quote","text":"Do not spoil what you have by desiring what you have not.","source":"Epicurus"},
  {"type":"quote","text":"He that is of a merry heart hath a continual feast.","source":"Proverbs 15:15, paraphrase"},
  {"type":"quote","text":"Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.","source":"Galatians 6:9, paraphrase"},
  {"type":"quote","text":"And let us consider how we may spur one another on toward love and good deeds.","source":"Hebrews 10:24, paraphrase"},
  {"type":"quote","text":"Above all, love each other deeply, because love covers over a multitude of sins.","source":"1 Peter 4:8, paraphrase"},
  {"type":"quote","text":"Carry each other's burdens, and in this way you will fulfill the law of Christ.","source":"Galatians 6:2, paraphrase"},
  {"type":"quote","text":"Do to others as you would have them do to you.","source":"Luke 6:31, paraphrase"},
  {"type":"quote","text":"Rejoice with those who rejoice; mourn with those who mourn.","source":"Romans 12:15, paraphrase"},
  {"type":"quote","text":"A friend loves at all times.","source":"Proverbs 17:17, paraphrase"},
  {"type":"quote","text":"Encourage one another and build each other up.","source":"1 Thessalonians 5:11, paraphrase"},
  {"type":"quote","text":"Simplicity is the ultimate sophistication.","source":"Attr. Leonardo da Vinci"},
  {"type":"quote","text":"Life is really simple, but we insist on making it complicated.","source":"Confucius"},
  {"type":"quote","text":"The ability to simplify means to eliminate the unnecessary so that the necessary may speak.","source":"Hans Hofmann"},
  {"type":"quote","text":"Our life is frittered away by detail. Simplify, simplify.","source":"Henry David Thoreau"},
  {"type":"quote","text":"Talk to yourself like you would to someone you love.","source":"Brené Brown"},
  {"type":"quote","text":"Be gentle with yourself, you're doing the best you can.","source":"Unknown"},
  {"type":"quote","text":"Self-compassion is simply giving the same kindness to ourselves that we would give to others.","source":"Christopher Germer"},
  {"type":"quote","text":"Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit.","source":"Ralph Marston"},
  {"type":"quote","text":"Almost everything will work again if you unplug it for a few minutes, including you.","source":"Anne Lamott"},
  {"type":"quote","text":"The comeback is always stronger than the setback.","source":"Unknown"},
  {"type":"quote","text":"Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong.","source":"Mandy Hale"},
  {"type":"quote","text":"A gem cannot be polished without friction, nor a man perfected without trials.","source":"Confucius"},
  {"type":"quote","text":"Diamonds are made under pressure.","source":"Attr. B.C. Forbes"},
  {"type":"quote","text":"He who has a why to live can bear almost any how.","source":"Friedrich Nietzsche"},
  {"type":"quote","text":"Words can inspire and words can destroy. Choose yours well.","source":"Robin Sharma"},
  {"type":"quote","text":"Speak the truth, but speak it in love.","source":"Ephesians 4:15, paraphrase"},
  {"type":"quote","text":"A word fitly spoken is like apples of gold in a setting of silver.","source":"Proverbs 25:11, paraphrase"},
  {"type":"quote","text":"Death and life are in the power of the tongue.","source":"Proverbs 18:21, paraphrase"},
  {"type":"quote","text":"An encouraging word can lift someone's spirit for weeks.","source":"Unknown"},
  {"type":"quote","text":"Words are, of course, the most powerful drug used by mankind.","source":"Rudyard Kipling"},
  {"type":"quote","text":"It takes courage to grow up and become who you really are.","source":"E.E. Cummings"},
  {"type":"quote","text":"Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'","source":"Attr. Mary Anne Radmacher"},
  {"type":"quote","text":"You cannot swim for new horizons until you have courage to lose sight of the shore.","source":"William Faulkner"},
  {"type":"quote","text":"One small crack does not mean that you are broken, it means that you were put to the test and you didn't fall apart.","source":"Linda Poindexter"},
  {"type":"quote","text":"Fear is a reaction. Courage is a decision.","source":"Attr. Winston Churchill"},
  {"type":"quote","text":"Empathy is seeing with the eyes of another, listening with the ears of another, and feeling with the heart of another.","source":"Alfred Adler"},
  {"type":"quote","text":"When people talk, listen completely. Most people never listen.","source":"Ernest Hemingway"},
  {"type":"quote","text":"Honesty is the first chapter in the book of wisdom.","source":"Thomas Jefferson"},
  {"type":"quote","text":"The truth will set you free, but first it will make you miserable.","source":"Attr. James A. Garfield"},
  {"type":"quote","text":"Three things cannot be long hidden: the sun, the moon, and the truth.","source":"Attr. Buddha"},
  {"type":"quote","text":"Time is the coin of your life. You spend it. Do not allow others to spend it for you.","source":"Carl Sandburg"},
  {"type":"quote","text":"Lost time is never found again.","source":"Benjamin Franklin"},
  {"type":"quote","text":"Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.","source":"Mother Teresa"},
  {"type":"quote","text":"The trouble is, you think you have time.","source":"Attr. Buddha"},
  {"type":"quote","text":"Do not let the memory of your years take away the promise of your years.","source":"Numbers 33:55, adapted"},
  {"type":"quote","text":"It's not the years in your life that count. It's the life in your years.","source":"Abraham Lincoln"},
  {"type":"quote","text":"Old friends pass away, new friends appear. It is just like the days. An old day passes, a new day arrives.","source":"Dalai Lama"},
  {"type":"quote","text":"You don't stop laughing because you grow old. You grow old because you stop laughing.","source":"Attr. George Bernard Shaw"},
  {"type":"quote","text":"Wrinkles should merely indicate where smiles have been.","source":"Mark Twain"},
  {"type":"quote","text":"A house is made of walls and beams; a home is built with love and dreams.","source":"Unknown"},
  {"type":"quote","text":"There is no place like home.","source":"John Howard Payne"},
  {"type":"quote","text":"Hospitality is one form of worship.","source":"Jewish proverb"},
  {"type":"quote","text":"When you open your door to someone, you're opening your heart a little too.","source":"Unknown"},
  {"type":"quote","text":"Purpose is the reason you journey. Passion is the fire that lights your way.","source":"Attr. Mary Morrissey"},
  {"type":"quote","text":"The two most important days in your life are the day you are born and the day you find out why.","source":"Mark Twain"},
  {"type":"quote","text":"Everyone has been made for some particular work, and the desire for that work has been put in every heart.","source":"Rumi"},
  {"type":"quote","text":"What you do makes a difference, and you have to decide what kind of difference you want to make.","source":"Jane Goodall"},
  {"type":"quote","text":"He who has begun has half done. Dare to be wise; begin!","source":"Horace"},
  {"type":"quote","text":"You don't have to be great to start, but you have to start to be great.","source":"Attr. Zig Ziglar"},
  {"type":"quote","text":"The way to get started is to quit talking and begin doing.","source":"Walt Disney"},
  {"type":"quote","text":"A year from now you may wish you had started today.","source":"Karen Lamb"},
  {"type":"quote","text":"Action is the foundational key to all success.","source":"Pablo Picasso"},
  {"type":"quote","text":"Community is much more than belonging to something; it's about doing something together that makes belonging matter.","source":"Brian Solis"},
  {"type":"quote","text":"No man is an island, entire of itself.","source":"John Donne"},
  {"type":"quote","text":"If you want to go fast, go alone. If you want to go far, go together.","source":"African proverb"},
  {"type":"quote","text":"It takes a village to raise a child.","source":"African proverb"},
  {"type":"quote","text":"Cast thy bread upon the waters: for thou shalt find it after many days.","source":"Ecclesiastes 11:1, paraphrase"},
  {"type":"quote","text":"Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap.","source":"Luke 6:38, paraphrase"},
  {"type":"quote","text":"Freely you have received; freely give.","source":"Matthew 10:8, paraphrase"},
  {"type":"quote","text":"Whoever is kind to the poor lends to the LORD, and he will reward them for what they have done.","source":"Proverbs 19:17, paraphrase"},
  {"type":"quote","text":"A generous person will prosper; whoever refreshes others will be refreshed.","source":"Proverbs 11:25, paraphrase"},
  {"type":"quote","text":"Two are better than one, because they have a good return for their work.","source":"Ecclesiastes 4:9, paraphrase"},
  {"type":"quote","text":"Let brotherly love continue. Be not forgetful to entertain strangers.","source":"Hebrews 13:1-2, paraphrase"},
  {"type":"quote","text":"Whatsoever thy hand findeth to do, do it with thy might.","source":"Ecclesiastes 9:10, KJV"},
  {"type":"quote","text":"Be still, and know that I am God.","source":"Psalm 46:10, KJV"},
  {"type":"quote","text":"The LORD is close to the brokenhearted and saves those who are crushed in spirit.","source":"Psalm 34:18, paraphrase"},
  {"type":"quote","text":"He heals the brokenhearted and binds up their wounds.","source":"Psalm 147:3, paraphrase"},
  {"type":"quote","text":"Cast all your anxiety on him because he cares for you.","source":"1 Peter 5:7, paraphrase"},
  {"type":"quote","text":"Come to me, all you who are weary and burdened, and I will give you rest.","source":"Matthew 11:28, paraphrase"},
  {"type":"quote","text":"The Lord is my shepherd; I shall not want.","source":"Psalm 23:1, KJV"},
  {"type":"quote","text":"This is the day which the LORD hath made; we will rejoice and be glad in it.","source":"Psalm 118:24, KJV"},
  {"type":"quote","text":"Weeping may endure for a night, but joy cometh in the morning.","source":"Psalm 30:5, KJV"},
  {"type":"quote","text":"I can do all things through Christ which strengtheneth me.","source":"Philippians 4:13, KJV"},
  {"type":"quote","text":"Be strong and of a good courage; be not afraid, neither be thou dismayed.","source":"Joshua 1:9, paraphrase"},
  {"type":"quote","text":"The joy of the Lord is your strength.","source":"Nehemiah 8:10, KJV"},
  {"type":"quote","text":"He giveth power to the faint; and to them that have no might he increaseth strength.","source":"Isaiah 40:29, KJV"},
  {"type":"quote","text":"They that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles.","source":"Isaiah 40:31, KJV"},
  {"type":"quote","text":"Trust in the LORD with all thine heart; and lean not unto thine own understanding.","source":"Proverbs 3:5, KJV"},
  {"type":"quote","text":"For I know the plans I have for you, plans to prosper you and not to harm you, plans to give you hope and a future.","source":"Jeremiah 29:11, paraphrase"},
  {"type":"quote","text":"The LORD is near to all who call on him.","source":"Psalm 145:18, paraphrase"},
  {"type":"quote","text":"Delight thyself also in the LORD; and he shall give thee the desires of thine heart.","source":"Psalm 37:4, KJV"},
];
