// 366 suggested "Barnabas moment" acts of kindness — one for every day of
// the year, including a leap day, with no repeats.
//
// Written to work for anyone, anywhere, regardless of age, relationship
// status, family situation, or living arrangement — a handful of targets
// that once assumed something about the reader (a spouse, kids of their
// own, a roommate) now carry a built-in alternative right in the phrase
// (e.g. "your partner (or the person closest to your heart)") instead of
// quietly excluding whoever that assumption doesn't fit. The moments span
// home, work, school, faith, neighborhood, and online life, and include
// gift-giving, introducing people to each other, and other ways to help
// someone feel valued, included, and seen — not just direct one-on-one
// kindness.

const BARNABAS_MOMENTS = [
  "Say something good about a family member to someone else today — the kind of thing that has a way of getting back to people.",
  "Tell a neighbor one specific thing you admire about them.",
  "Really listen to someone going through a hard season today, without planning what you'll say next.",
  "Send a delivery driver a message telling them exactly why you're grateful for them.",
  "Do a small task for an elderly neighbor without being asked.",
  "Tell someone who helped you once exactly what makes them valuable to the people around them, not just what they do.",
  "Share something hopeful with someone sitting alone — they might need it today.",
  "Give someone who looks tired today your full attention for five minutes today, phone away.",
  "Surprise a child in your life with a small kindness today, no reason needed.",
  "Pay for something small for a first responder today — a coffee, a meal, a fare — without making it a big deal.",
  "Ask your local barista or cashier how they're really doing, and wait for the real answer.",
  "Surprise a delivery driver with a small kindness today, no reason needed.",
  "Speak a word of hope over your local barista or cashier today.",
  "Tell someone in your household three things you appreciate about them today, one at a time.",
  "Check in on a small business owner nearby just to see how they're really doing.",
  "Celebrate a win someone in your community had today — say it out loud.",
  "Check in on a coworker having a rough week just to see how they're really doing.",
  "Say something good about a coworker to someone else today — the kind of thing that has a way of getting back to people.",
  "Cook or prepare a meal for someone who's had a hard week, even if it's simple.",
  "Give a mentor from your past your full attention for five minutes today, phone away.",
  "Make time today just for a mentor from your past, with nothing else competing for your attention.",
  "Say a genuine 'well done' to someone doing a job most people walk past without noticing.",
  "Surprise a mentor from your past with a small kindness today, no reason needed.",
  "Speak a word of hope over a neighbor today.",
  "Bring someone in your community something small — a coffee, a snack, a kind word.",
  "Thank someone going through a hard season for something you don't usually say thank you for.",
  "Speak a word of hope over a teacher today.",
  "Tidy or pick up litter in a shared space today without being asked or thanked for it.",
  "Write your sibling (or someone who feels like one) a short note of encouragement and leave it where they'll find it.",
  "Let a child in your life know you're thinking of them, unprompted.",
  "Say something good about someone new to your city to someone else today — the kind of thing that has a way of getting back to people.",
  "Ask a mentor from your past how they're really doing, and wait for the real answer.",
  "Give a parent you know a small gift today — nothing expensive, just something that shows you noticed them.",
  "Let a family member know you're thinking of them, unprompted.",
  "Let an elderly neighbor know you're thinking of them, unprompted.",
  "Tell someone new exactly what makes them valuable to the people around them, not just what they do.",
  "Make time today just for a service worker, with nothing else competing for your attention.",
  "Tell someone new one specific thing you admire about them.",
  "Really listen to a caregiver today, without planning what you'll say next.",
  "Compliment the effort your partner (or the person closest to your heart) is putting in, not just what they achieved.",
  "Bring your sibling (or someone who feels like one) something small — a coffee, a snack, a kind word.",
  "Tell someone quietly struggling how they've shaped who you are.",
  "Surprise your local barista or cashier with a small kindness today, no reason needed.",
  "Give money, time, or goods to a cause someone close to you cares about, in their honor.",
  "Thank someone whose work usually goes unnoticed for something you don't usually say thank you for.",
  "Speak a word of hope over a small business owner nearby today.",
  "Give credit out loud today to someone whose work usually gets overlooked.",
  "Show up in person for something instead of sending a text — a visit, a call, a face-to-face conversation.",
  "Pay for something small for a child in your life today — a coffee, a meal, a fare — without making it a big deal.",
  "Recommend someone who looks tired today for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Make time today just for someone who helped you once, with nothing else competing for your attention.",
  "Recommend someone you disagreed with recently for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Say something good about your pastor or a spiritual leader to someone else today — the kind of thing that has a way of getting back to people.",
  "Ask someone teaching themselves something hard right now how they're really doing, and wait for the real answer.",
  "Ask someone sitting alone how they're really doing, and wait for the real answer.",
  "Tell a mentor from your past how they've shaped who you are.",
  "Pay for something small for an online friend today — a coffee, a meal, a fare — without making it a big deal.",
  "Tell someone whose work usually goes unnoticed exactly what makes them valuable to the people around them, not just what they do.",
  "Tell a delivery driver exactly what makes them valuable to the people around them, not just what they do.",
  "Make time today just for your parent (or whoever raised you), with nothing else competing for your attention.",
  "Write your parent (or whoever raised you) a short note of encouragement and leave it where they'll find it.",
  "Write a neighbor a short note of encouragement and leave it where they'll find it.",
  "Thank a classmate for something you don't usually say thank you for.",
  "Surprise someone who helped you once with a small kindness today, no reason needed.",
  "Let someone who helped you once know you're thinking of them, unprompted.",
  "Ask someone you disagreed with recently how they're really doing, and wait for the real answer.",
  "Ask your partner (or the person closest to your heart) how they're really doing, and wait for the real answer.",
  "Do a small task for a small business owner nearby without being asked.",
  "Include a service worker in something today — a meal, a plan, a conversation — so they know they belong.",
  "Include a stranger in something today — a meal, a plan, a conversation — so they know they belong.",
  "Ask someone new how they're really doing, and wait for the real answer.",
  "Let a teacher know you're thinking of them, unprompted.",
  "Surprise a service worker with a small kindness today, no reason needed.",
  "Ask someone to teach you something they know and you don't — and really let them teach you.",
  "Send a neighbor a message telling them exactly why you're grateful for them.",
  "Speak a word of hope over someone in your community today.",
  "Share something hopeful with a new coworker or classmate — they might need it today.",
  "Check in on a child in your life just to see how they're really doing.",
  "Pay for something small for someone teaching themselves something hard right now today — a coffee, a meal, a fare — without making it a big deal.",
  "Bring your partner (or the person closest to your heart) something small — a coffee, a snack, a kind word.",
  "Celebrate a win your local barista or cashier had today — say it out loud.",
  "Compliment the effort a coworker having a rough week is putting in, not just what they achieved.",
  "Pay for something small for a mentor from your past today — a coffee, a meal, a fare — without making it a big deal.",
  "Bring someone who looks tired today something small — a coffee, a snack, a kind word.",
  "Forgive a nurse or doctor you know quietly today, even if they never know it.",
  "Do a small task for an old friend you've lost touch with without being asked.",
  "Do a small task for someone sitting alone without being asked.",
  "Forgive someone teaching themselves something hard right now quietly today, even if they never know it.",
  "Send someone sitting alone a message telling them exactly why you're grateful for them.",
  "Really listen to a close friend today, without planning what you'll say next.",
  "Offer to help an old friend you've lost touch with with something they've been putting off.",
  "Really listen to someone teaching themselves something hard right now today, without planning what you'll say next.",
  "Write someone whose work usually goes unnoticed a short note of encouragement and leave it where they'll find it.",
  "Compliment the effort a coworker is putting in, not just what they achieved.",
  "Tell an old friend you've lost touch with exactly what makes them valuable to the people around them, not just what they do.",
  "Write someone who looks tired today a short note of encouragement and leave it where they'll find it.",
  "Offer to help your parent (or whoever raised you) with something they've been putting off.",
  "Let a volunteer know you're thinking of them, unprompted.",
  "Make time today just for a coworker, with nothing else competing for your attention.",
  "Send someone in your community a message telling them exactly why you're grateful for them.",
  "Recommend a caregiver for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Compliment the effort a caregiver is putting in, not just what they achieved.",
  "Tell a coworker having a rough week one specific thing you admire about them.",
  "Give a parent you know your full attention for five minutes today, phone away.",
  "Pay for something small for someone in your community today — a coffee, a meal, a fare — without making it a big deal.",
  "Offer to help a volunteer with something they've been putting off.",
  "Bring someone going through a hard season something small — a coffee, a snack, a kind word.",
  "Really listen to someone sitting alone today, without planning what you'll say next.",
  "Include an online friend in something today — a meal, a plan, a conversation — so they know they belong.",
  "Send a first responder a message telling them exactly why you're grateful for them.",
  "Surprise a nurse or doctor you know with a small kindness today, no reason needed.",
  "Give a caregiver your full attention for five minutes today, phone away.",
  "Thank a parent you know for something you don't usually say thank you for.",
  "Ask a coworker how they're really doing, and wait for the real answer.",
  "Speak a word of hope over a close friend today.",
  "Check in on your local barista or cashier just to see how they're really doing.",
  "Offer to help a stranger with something they've been putting off.",
  "Tell a service worker one specific thing you admire about them.",
  "Tell someone who looks tired today one specific thing you admire about them.",
  "Thank a teacher for something you don't usually say thank you for.",
  "Compliment the effort someone quietly struggling is putting in, not just what they achieved.",
  "Pay for something small for a classmate today — a coffee, a meal, a fare — without making it a big deal.",
  "Tell your local barista or cashier exactly what makes them valuable to the people around them, not just what they do.",
  "Ask a close friend how they're really doing, and wait for the real answer.",
  "Thank someone you disagreed with recently for something you don't usually say thank you for.",
  "Speak a word of hope over a caregiver today.",
  "Give a delivery driver a small gift today — nothing expensive, just something that shows you noticed them.",
  "Make time today just for a family member, with nothing else competing for your attention.",
  "Share something hopeful with a family member — they might need it today.",
  "Celebrate a win a parent you know had today — say it out loud.",
  "Include a parent you know in something today — a meal, a plan, a conversation — so they know they belong.",
  "Celebrate a win a caregiver had today — say it out loud.",
  "Tell someone quietly struggling one specific thing you admire about them.",
  "Really listen to someone whose work usually goes unnoticed today, without planning what you'll say next.",
  "Surprise someone sitting alone with a small kindness today, no reason needed.",
  "Bring a child in your life something small — a coffee, a snack, a kind word.",
  "Share a meal or a coffee with someone who might otherwise eat alone today.",
  "Say something good about a delivery driver to someone else today — the kind of thing that has a way of getting back to people.",
  "Speak a word of hope over someone going through a hard season today.",
  "Celebrate a win a close friend had today — say it out loud.",
  "Compliment the effort someone in your community is putting in, not just what they achieved.",
  "Tell a classmate one specific thing you admire about them.",
  "Share something hopeful with someone you live with (or a close friend, if you live alone) — they might need it today.",
  "Share something hopeful with someone going through a hard season — they might need it today.",
  "Really listen to a small business owner nearby today, without planning what you'll say next.",
  "Include someone whose work usually goes unnoticed in something today — a meal, a plan, a conversation — so they know they belong.",
  "Forgive your local barista or cashier quietly today, even if they never know it.",
  "Celebrate a win a coworker had today — say it out loud.",
  "Forgive a teacher quietly today, even if they never know it.",
  "Tell a small business owner nearby one specific thing you admire about them.",
  "Forgive someone who helped you once quietly today, even if they never know it.",
  "Offer to help a mentor from your past with something they've been putting off.",
  "Forgive a classmate quietly today, even if they never know it.",
  "Give someone who helped you once a small gift today — nothing expensive, just something that shows you noticed them.",
  "Reach out to someone you admire from a distance and tell them so directly.",
  "Make time today just for someone who looks tired today, with nothing else competing for your attention.",
  "Ask a caregiver how they're really doing, and wait for the real answer.",
  "Celebrate a win someone teaching themselves something hard right now had today — say it out loud.",
  "Offer to help an elderly neighbor with something they've been putting off.",
  "Check in on someone you live with (or a close friend, if you live alone) just to see how they're really doing.",
  "Tell someone new to your city how they've shaped who you are.",
  "Pay for something small for someone you live with (or a close friend, if you live alone) today — a coffee, a meal, a fare — without making it a big deal.",
  "Surprise a family member with a small kindness today, no reason needed.",
  "Write a letter — an actual paper letter — to someone who would never expect one.",
  "Speak a word of hope over an old friend you've lost touch with today.",
  "Offer to help someone quietly struggling with something they've been putting off.",
  "Give someone whose work usually goes unnoticed a small gift today — nothing expensive, just something that shows you noticed them.",
  "Recommend a child in your life for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Tell someone you disagreed with recently one specific thing you admire about them.",
  "Tell a volunteer one specific thing you admire about them.",
  "Give an old friend you've lost touch with a small gift today — nothing expensive, just something that shows you noticed them.",
  "Really listen to someone you live with (or a close friend, if you live alone) today, without planning what you'll say next.",
  "Share something hopeful with your parent (or whoever raised you) — they might need it today.",
  "Really listen to someone who looks tired today today, without planning what you'll say next.",
  "Give a small business owner nearby your full attention for five minutes today, phone away.",
  "Let a small business owner nearby know you're thinking of them, unprompted.",
  "Check in on a volunteer just to see how they're really doing.",
  "Thank your sibling (or someone who feels like one) for something you don't usually say thank you for.",
  "Compliment the effort someone you live with (or a close friend, if you live alone) is putting in, not just what they achieved.",
  "Make time today just for your partner (or the person closest to your heart), with nothing else competing for your attention.",
  "Give your local barista or cashier a small gift today — nothing expensive, just something that shows you noticed them.",
  "Check in on someone sitting alone just to see how they're really doing.",
  "Offer to help someone you disagreed with recently with something they've been putting off.",
  "Offer to carry, lift, fix, or fetch something for someone struggling with it today.",
  "Give up your seat, your place in line, or your turn for someone today, cheerfully.",
  "Pay for something small for a stranger today — a coffee, a meal, a fare — without making it a big deal.",
  "Offer to help a neighbor with something they've been putting off.",
  "Give a neighbor a small gift today — nothing expensive, just something that shows you noticed them.",
  "Compliment the effort an online friend is putting in, not just what they achieved.",
  "Tell a caregiver exactly what makes them valuable to the people around them, not just what they do.",
  "Make time today just for your pastor or a spiritual leader, with nothing else competing for your attention.",
  "Do a small task for a first responder without being asked.",
  "Ask a coworker having a rough week how they're really doing, and wait for the real answer.",
  "Forgive a first responder quietly today, even if they never know it.",
  "Celebrate a win a volunteer had today — say it out loud.",
  "Share something hopeful with someone in your community — they might need it today.",
  "Compliment the effort a child in your life is putting in, not just what they achieved.",
  "Give a mentor from your past a small gift today — nothing expensive, just something that shows you noticed them.",
  "Tell a stranger one specific thing you admire about them.",
  "Forgive an online friend quietly today, even if they never know it.",
  "Write someone quietly struggling a short note of encouragement and leave it where they'll find it.",
  "Give a first responder your full attention for five minutes today, phone away.",
  "Include someone who helped you once in something today — a meal, a plan, a conversation — so they know they belong.",
  "Bring a volunteer something small — a coffee, a snack, a kind word.",
  "Pay for something small for a teacher today — a coffee, a meal, a fare — without making it a big deal.",
  "Let a classmate know you're thinking of them, unprompted.",
  "Let a stranger know you're thinking of them, unprompted.",
  "Thank someone who helped you once for something you don't usually say thank you for.",
  "Tell your parent (or whoever raised you) how they've shaped who you are.",
  "Write a small business owner nearby a short note of encouragement and leave it where they'll find it.",
  "Forgive someone quietly struggling quietly today, even if they never know it.",
  "Share something hopeful with someone who looks tired today — they might need it today.",
  "Bring a small business owner nearby something small — a coffee, a snack, a kind word.",
  "Give an old friend you've lost touch with your full attention for five minutes today, phone away.",
  "Write someone you disagreed with recently a short note of encouragement and leave it where they'll find it.",
  "Ask a family member how they're really doing, and wait for the real answer.",
  "Send a family member a message telling them exactly why you're grateful for them.",
  "Write a stranger a short note of encouragement and leave it where they'll find it.",
  "Pay for something small for a neighbor today — a coffee, a meal, a fare — without making it a big deal.",
  "Celebrate a win someone quietly struggling had today — say it out loud.",
  "Recommend someone who helped you once for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Check in on someone who looks tired today just to see how they're really doing.",
  "Tell a nurse or doctor you know exactly what makes them valuable to the people around them, not just what they do.",
  "Compliment the effort someone going through a hard season is putting in, not just what they achieved.",
  "Give your local barista or cashier your full attention for five minutes today, phone away.",
  "Give someone new a small gift today — nothing expensive, just something that shows you noticed them.",
  "Give your pastor or a spiritual leader a small gift today — nothing expensive, just something that shows you noticed them.",
  "Recommend a family member for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Pay for something small for a parent you know today — a coffee, a meal, a fare — without making it a big deal.",
  "Recommend a first responder for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Make time today just for your sibling (or someone who feels like one), with nothing else competing for your attention.",
  "Surprise an online friend with a small kindness today, no reason needed.",
  "Speak a word of hope over a parent you know today.",
  "Give a delivery driver your full attention for five minutes today, phone away.",
  "Write a genuine, specific recommendation or reference for someone who could use one.",
  "Really listen to your parent (or whoever raised you) today, without planning what you'll say next.",
  "Tell someone who looks tired today how they've shaped who you are.",
  "Share something hopeful with a coworker having a rough week — they might need it today.",
  "Surprise a caregiver with a small kindness today, no reason needed.",
  "Celebrate a win someone sitting alone had today — say it out loud.",
  "Offer to babysit, pet-sit, house-sit, or cover a responsibility for someone so they can have a break.",
  "Compliment the effort someone you disagreed with recently is putting in, not just what they achieved.",
  "Really listen to someone new to your city today, without planning what you'll say next.",
  "Check in on a first responder just to see how they're really doing.",
  "Tell a volunteer how they've shaped who you are.",
  "Send someone whose work usually goes unnoticed a message telling them exactly why you're grateful for them.",
  "Recommend your sibling (or someone who feels like one) for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Tell your partner (or the person closest to your heart) how they've shaped who you are.",
  "Forgive a neighbor quietly today, even if they never know it.",
  "Tell someone you live with (or a close friend, if you live alone) exactly what makes them valuable to the people around them, not just what they do.",
  "Forgive a coworker having a rough week quietly today, even if they never know it.",
  "Include someone you live with (or a close friend, if you live alone) in something today — a meal, a plan, a conversation — so they know they belong.",
  "Check in on someone going through a hard season just to see how they're really doing.",
  "Compliment the effort a volunteer is putting in, not just what they achieved.",
  "Send your sibling (or someone who feels like one) a message telling them exactly why you're grateful for them.",
  "Do a small task for your parent (or whoever raised you) without being asked.",
  "Tell an old friend you've lost touch with how they've shaped who you are.",
  "Say something good about a new coworker or classmate to someone else today — the kind of thing that has a way of getting back to people.",
  "Write a thank-you note to someone whose name you don't actually know — a delivery person, a cleaner, a security guard — and find a way to get it to them.",
  "Do a small task for someone who helped you once without being asked.",
  "Do a small task for a family member without being asked.",
  "Tell someone you live with (or a close friend, if you live alone) one specific thing you admire about them.",
  "Write a mentor from your past a short note of encouragement and leave it where they'll find it.",
  "Ask a classmate how they're really doing, and wait for the real answer.",
  "Let a coworker having a rough week know you're thinking of them, unprompted.",
  "Include your parent (or whoever raised you) in something today — a meal, a plan, a conversation — so they know they belong.",
  "Really listen to a mentor from your past today, without planning what you'll say next.",
  "Plan a small surprise — a note, a treat, a favor — for someone who always plans things for everyone else.",
  "Share something hopeful with a close friend — they might need it today.",
  "Give away something you own but rarely use to someone who could actually use it.",
  "Really listen to a stranger today, without planning what you'll say next.",
  "Share something hopeful with a nurse or doctor you know — they might need it today.",
  "Send someone new a message telling them exactly why you're grateful for them.",
  "Tell an elderly neighbor how they've shaped who you are.",
  "Leave a generous tip today for someone in a service job, and let them see you mean it.",
  "Give a classmate your full attention for five minutes today, phone away.",
  "Offer to help a service worker with something they've been putting off.",
  "Do a small task for an online friend without being asked.",
  "Offer to help someone in your community with something they've been putting off.",
  "Include someone sitting alone in something today — a meal, a plan, a conversation — so they know they belong.",
  "Thank an old friend you've lost touch with for something you don't usually say thank you for.",
  "Recommend your parent (or whoever raised you) for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Surprise someone new to your city with a small kindness today, no reason needed.",
  "Say something good about someone quietly struggling to someone else today — the kind of thing that has a way of getting back to people.",
  "Give a volunteer your full attention for five minutes today, phone away.",
  "Compliment the effort a classmate is putting in, not just what they achieved.",
  "Tell a family member how they've shaped who you are.",
  "Put your phone away completely during your next conversation today, whoever it's with.",
  "Celebrate a win someone you disagreed with recently had today — say it out loud.",
  "Bring a stranger something small — a coffee, a snack, a kind word.",
  "Tell a neighbor how they've shaped who you are.",
  "Write your pastor or a spiritual leader a short note of encouragement and leave it where they'll find it.",
  "Say something good about a first responder to someone else today — the kind of thing that has a way of getting back to people.",
  "Write someone new to your city a short note of encouragement and leave it where they'll find it.",
  "Bring an elderly neighbor something small — a coffee, a snack, a kind word.",
  "Celebrate a win an old friend you've lost touch with had today — say it out loud.",
  "Really listen to your partner (or the person closest to your heart) today, without planning what you'll say next.",
  "Include someone new in something today — a meal, a plan, a conversation — so they know they belong.",
  "Ask a nurse or doctor you know how they're really doing, and wait for the real answer.",
  "Do a small task for someone you live with (or a close friend, if you live alone) without being asked.",
  "Do a small task for a nurse or doctor you know without being asked.",
  "Leave a kind, honest review or shout-out for a local business, service, or person who did right by you.",
  "Bring a classmate something small — a coffee, a snack, a kind word.",
  "Introduce two people in your life who don't know each other yet but who you think would genuinely get along or help each other.",
  "Celebrate a win someone new had today — say it out loud.",
  "Give a nurse or doctor you know your full attention for five minutes today, phone away.",
  "Forgive a coworker quietly today, even if they never know it.",
  "Text someone you haven't spoken to in a long time just to say you still think about them.",
  "Do a small task for someone whose work usually goes unnoticed without being asked.",
  "Give a close friend your full attention for five minutes today, phone away.",
  "Bring a new coworker or classmate something small — a coffee, a snack, a kind word.",
  "Say something good about someone you live with (or a close friend, if you live alone) to someone else today — the kind of thing that has a way of getting back to people.",
  "Surprise a close friend with a small kindness today, no reason needed.",
  "Let someone go ahead of you today — in traffic, in line, in a conversation — and mean it.",
  "Tell an online friend exactly what makes them valuable to the people around them, not just what they do.",
  "Let a first responder know you're thinking of them, unprompted.",
  "Cover a small cost for someone today without telling them it was you.",
  "Thank an elderly neighbor for something you don't usually say thank you for.",
  "Pay for something small for a close friend today — a coffee, a meal, a fare — without making it a big deal.",
  "Let someone new to your city know you're thinking of them, unprompted.",
  "Leave an encouraging comment on something someone made or posted, publicly, where others will see it too.",
  "Offer to help your sibling (or someone who feels like one) with something they've been putting off.",
  "Tell a stranger how they've shaped who you are.",
  "Compliment the effort a small business owner nearby is putting in, not just what they achieved.",
  "Say something good about someone you disagreed with recently to someone else today — the kind of thing that has a way of getting back to people.",
  "Ask your sibling (or someone who feels like one) how they're really doing, and wait for the real answer.",
  "Surprise a first responder with a small kindness today, no reason needed.",
  "Write your local barista or cashier a short note of encouragement and leave it where they'll find it.",
  "Compliment the effort someone sitting alone is putting in, not just what they achieved.",
  "Bring something to share with everyone in a space you're part of today — home, work, class, or your street.",
  "Tell someone going through a hard season one specific thing you admire about them.",
  "Thank a stranger for something you don't usually say thank you for.",
  "Say something good about a volunteer to someone else today — the kind of thing that has a way of getting back to people.",
  "Celebrate a win a first responder had today — say it out loud.",
  "Let a neighbor know you're thinking of them, unprompted.",
  "Offer a ride, a lift, or help getting somewhere to someone who needs it today.",
  "Do a small task for a delivery driver without being asked.",
  "Pay for something small for a small business owner nearby today — a coffee, a meal, a fare — without making it a big deal.",
  "Offer to help someone sitting alone with something they've been putting off.",
  "Give someone in your community your full attention for five minutes today, phone away.",
  "Celebrate a win someone who helped you once had today — say it out loud.",
  "Pay for something small for your sibling (or someone who feels like one) today — a coffee, a meal, a fare — without making it a big deal.",
  "Recommend someone quietly struggling for something real — a job lead, an opportunity, an introduction you can actually make happen.",
  "Offer to help your partner (or the person closest to your heart) with something they've been putting off.",
  "Check in on a new coworker or classmate just to see how they're really doing.",
  "Include someone who looks tired today in something today — a meal, a plan, a conversation — so they know they belong.",
  "Offer your specific skill or knowledge to someone for free today, even for twenty minutes.",
  "Check in on someone you disagreed with recently just to see how they're really doing.",
  "Bring a nurse or doctor you know something small — a coffee, a snack, a kind word.",
  "Say something good about a parent you know to someone else today — the kind of thing that has a way of getting back to people.",
  "Give an online friend your full attention for five minutes today, phone away.",
  "Tell a service worker exactly what makes them valuable to the people around them, not just what they do.",
  "Tell a parent you know exactly what makes them valuable to the people around them, not just what they do.",
  "Speak a word of hope over someone teaching themselves something hard right now today.",
  "Do a small task for your pastor or a spiritual leader without being asked.",
  "Really listen to a service worker today, without planning what you'll say next.",
  "Do a small task for your local barista or cashier without being asked.",
  "Bring a parent you know something small — a coffee, a snack, a kind word.",
  "Write your partner (or the person closest to your heart) a short note of encouragement and leave it where they'll find it.",
  "Say something good about a mentor from your past to someone else today — the kind of thing that has a way of getting back to people.",
  "Forgive someone you disagreed with recently quietly today, even if they never know it.",
  "Tell a teacher one specific thing you admire about them.",
  "Say something good about a coworker having a rough week to someone else today — the kind of thing that has a way of getting back to people.",
  "Bring someone you live with (or a close friend, if you live alone) something small — a coffee, a snack, a kind word.",
  "Ask someone how their family is doing, by name, and actually listen to the answer.",
  "Say something good about a neighbor to someone else today — the kind of thing that has a way of getting back to people.",
];
